package main

import (
	"bytes"
	"encoding/json"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"testing"

	"github.com/marmutapp/superbased-observer/internal/tooltax"
)

// committedDir is where the generated artifacts live, relative to this
// package dir. Their names come from the generator itself (jsonName /
// typesName / vectorsName), so a fourth artifact cannot be added without
// this test covering it.
const committedDir = "../../shared/lib"

// tokensPath is the stylesheet that must define an --act-* var for every
// canonical category, in both themes.
const tokensPath = "../../shared/styles/tokens.css"

// The two theme blocks in tokens.css. A category colour missing from
// either one renders as the meta gray in that theme only — the kind of
// half-applied change a single grep would miss.
var themeSelectors = []string{
	`:root[data-theme="dark"] {`,
	`:root[data-theme="light"] {`,
}

func generateOrFail(t *testing.T) []byte {
	t.Helper()
	data, err := generate()
	if err != nil {
		t.Fatalf("generate: %v", err)
	}
	return data
}

func generateAllOrFail(t *testing.T) []artifact {
	t.Helper()
	arts, err := generateAll()
	if err != nil {
		t.Fatalf("generateAll: %v", err)
	}
	return arts
}

func generateVectorsOrFail(t *testing.T) vectorsDoc {
	t.Helper()
	data, err := generateVectors()
	if err != nil {
		t.Fatalf("generateVectors: %v", err)
	}
	var v vectorsDoc
	if err := json.Unmarshal(data, &v); err != nil {
		t.Fatalf("unmarshal vectors: %v", err)
	}
	return v
}

func generateTypesOrFail(t *testing.T) string {
	t.Helper()
	data, err := generateTypes()
	if err != nil {
		t.Fatalf("generateTypes: %v", err)
	}
	return string(data)
}

func decodeOrFail(t *testing.T, data []byte) doc {
	t.Helper()
	var d doc
	if err := json.Unmarshal(data, &d); err != nil {
		t.Fatalf("unmarshal generated JSON: %v", err)
	}
	return d
}

// TestGenerateIsDeterministic is the precondition for the whole drift
// gate: if generateAll() were order-unstable (a ranged map, a clock, an
// environment read) `make verify-taxonomy-build` would fail at random.
func TestGenerateIsDeterministic(t *testing.T) {
	first := generateAllOrFail(t)
	for run := 2; run <= 4; run++ {
		next := generateAllOrFail(t)
		if len(next) != len(first) {
			t.Fatalf("run %d emitted %d artifacts, run 1 emitted %d", run, len(next), len(first))
		}
		for i := range first {
			if next[i].Name != first[i].Name {
				t.Fatalf("run %d artifact %d is %q, run 1 had %q",
					run, i, next[i].Name, first[i].Name)
			}
			if !bytes.Equal(next[i].Data, first[i].Data) {
				t.Fatalf("run %d differs from run 1 in %s:\n--- run 1 ---\n%s\n--- run %d ---\n%s",
					run, first[i].Name, first[i].Data, run, next[i].Data)
			}
		}
	}
}

// TestGeneratedMatchesCommitted is the in-test half of the CI gate: it
// fails the Go suite (not just the shell gate) when somebody changes
// tooltax without running `make taxonomy-build`. It covers EVERY
// artifact — the data file, the type file and the TS gate's vectors —
// so a stale vector file can't quietly let the TS gate pass against
// last month's expectations.
func TestGeneratedMatchesCommitted(t *testing.T) {
	arts := generateAllOrFail(t)
	if len(arts) != 3 {
		t.Fatalf("expected 3 artifacts, got %d", len(arts))
	}
	for _, a := range arts {
		path := filepath.Join(committedDir, a.Name)
		want, err := os.ReadFile(path)
		if err != nil {
			t.Errorf("read committed %s: %v", path, err)
			continue
		}
		if !bytes.Equal(a.Data, want) {
			t.Errorf("%s is stale — run `make taxonomy-build` and commit.\n"+
				"committed %d bytes, regenerated %d bytes", path, len(want), len(a.Data))
		}
	}
}

// TestTrailingNewlineDiscipline pins the byte-level shape the gate diffs:
// valid JSON, 2-space indent, exactly one trailing newline.
func TestTrailingNewlineDiscipline(t *testing.T) {
	data := generateOrFail(t)
	if !json.Valid(data) {
		t.Fatal("generated bytes are not valid JSON")
	}
	if !bytes.HasSuffix(data, []byte("\n")) {
		t.Error("generated file does not end with a newline")
	}
	if bytes.HasSuffix(data, []byte("\n\n")) {
		t.Error("generated file ends with more than one newline")
	}
	if !bytes.Contains(data, []byte("\n  \"categories\": [")) {
		t.Error("generated file is not 2-space indented")
	}
}

// TestRegistryMirrorsTooltax pins the payload itself: every canonical
// action type, with tooltax's own category and label, and nothing
// invented locally.
func TestRegistryMirrorsTooltax(t *testing.T) {
	d := decodeOrFail(t, generateOrFail(t))

	want := tooltax.ActionTypes()
	if len(d.ActionTypes) != len(want) {
		t.Errorf("emitted %d action types, tooltax has %d", len(d.ActionTypes), len(want))
	}
	for _, at := range want {
		got, ok := d.ActionTypes[at]
		if !ok {
			t.Errorf("action type %q missing from the generated registry", at)
			continue
		}
		meta, _ := tooltax.MetaForActionType(at)
		if got.Category != meta.Category || got.Label != meta.Label {
			t.Errorf("action type %q emitted as {%q,%q}; tooltax says {%q,%q}",
				at, got.Category, got.Label, meta.Category, meta.Label)
		}
	}

	if diff := strings.Join(d.Categories, ","); diff != strings.Join(tooltax.Categories(), ",") {
		t.Errorf("categories = [%s]; tooltax.Categories() = [%s]",
			diff, strings.Join(tooltax.Categories(), ","))
	}
	if d.FallbackCategory != tooltax.CategoryForActionType(probeUnregistered) {
		t.Errorf("fallbackCategory = %q; tooltax falls back to %q",
			d.FallbackCategory, tooltax.CategoryForActionType(probeUnregistered))
	}

	known := make(map[string]struct{}, len(d.Categories))
	for _, c := range d.Categories {
		known[c] = struct{}{}
	}
	if _, ok := known[d.FallbackCategory]; !ok {
		t.Errorf("fallbackCategory %q is not in the emitted category list", d.FallbackCategory)
	}
	for at, meta := range d.ActionTypes {
		if _, ok := known[meta.Category]; !ok {
			t.Errorf("action type %q has category %q, which is not in the emitted category list",
				at, meta.Category)
		}
	}
}

// TestSurfacesMirrorTooltax pins the WP-T5 surface list — the §7
// "Surface waits for WP-T5" hook. It is DATA (the key space the
// dashboard renders /api/tools/breakdown's by_surface histogram in), not
// a re-declaration: every value comes from tooltax.Surfaces(), in order.
func TestSurfacesMirrorTooltax(t *testing.T) {
	d := decodeOrFail(t, generateOrFail(t))
	want := tooltax.Surfaces()
	if len(d.Surfaces) != len(want) {
		t.Fatalf("emitted %d surfaces, tooltax has %d", len(d.Surfaces), len(want))
	}
	for i, s := range want {
		if d.Surfaces[i] != string(s) {
			t.Errorf("surface %d = %q; tooltax says %q", i, d.Surfaces[i], s)
		}
	}
}

// TestToolCoverageMirrorsTooltax pins the WP-T5 per-adapter capture-depth
// map: exactly the tools tooltax declares rows for, each with
// CategoriesForTool's answer verbatim, and every category drawn from the
// emitted canonical list.
func TestToolCoverageMirrorsTooltax(t *testing.T) {
	d := decodeOrFail(t, generateOrFail(t))
	tools := tooltax.Tools()
	if len(d.ToolCoverage) != len(tools) {
		t.Errorf("emitted coverage for %d tools, tooltax declares %d", len(d.ToolCoverage), len(tools))
	}
	known := make(map[string]struct{}, len(d.Categories))
	for _, c := range d.Categories {
		known[c] = struct{}{}
	}
	for _, tool := range tools {
		got, ok := d.ToolCoverage[tool]
		if !ok {
			t.Errorf("tool %q missing from the emitted coverage map", tool)
			continue
		}
		want := tooltax.CategoriesForTool(tool)
		if strings.Join(got.Categories, ",") != strings.Join(want, ",") {
			t.Errorf("tool %q coverage = [%s]; tooltax says [%s]",
				tool, strings.Join(got.Categories, ","), strings.Join(want, ","))
		}
		for _, c := range got.Categories {
			if _, ok := known[c]; !ok {
				t.Errorf("tool %q coverage has category %q, which is not in the emitted category list", tool, c)
			}
		}
	}
	// The honest zero: a tool with no declared vocabulary is ABSENT, not
	// present with an empty list, so the dashboard can tell "shallow
	// capture" from "not mapped yet". The five browser-rail `*-web` tools
	// are the live instance of that case.
	if _, ok := d.ToolCoverage["chatgpt-web"]; ok {
		t.Error("chatgpt-web has no tooltax rows but appears in the coverage map")
	}
}

// TestToolCoverageIsNotTheNativeTable pins the plan's §7 sizing decision:
// the emitted coverage map is the DERIVED per-tool category set (~30
// short arrays), never the ~1,074-row (tool, native) table, which the
// browser has no use for and which would be dead bundle weight.
func TestToolCoverageIsNotTheNativeTable(t *testing.T) {
	d := decodeOrFail(t, generateOrFail(t))
	maxCats := len(tooltax.Categories())
	for tool, cov := range d.ToolCoverage {
		if len(cov.Categories) > maxCats {
			t.Errorf("tool %q emitted %d entries; a coverage list cannot exceed the %d canonical categories",
				tool, len(cov.Categories), maxCats)
		}
	}
	// And no native tool NAME may appear in the emitted bytes. Sourced
	// from the table itself rather than hand-picked, minus the names that
	// legitimately coincide with a canonical action type (`read_file`,
	// `web_search`, …) or with a tool id, which the file does emit.
	data := generateOrFail(t)
	skip := map[string]struct{}{}
	for _, at := range tooltax.ActionTypes() {
		skip[at] = struct{}{}
	}
	for _, tool := range tooltax.Tools() {
		skip[tool] = struct{}{}
	}
	for _, c := range tooltax.Categories() {
		skip[c] = struct{}{}
	}
	for _, s := range tooltax.Surfaces() {
		skip[string(s)] = struct{}{}
	}
	leaked := 0
	for _, e := range tooltax.Table() {
		if _, ok := skip[e.Native]; ok {
			continue
		}
		if bytes.Contains(data, []byte(`"`+e.Native+`"`)) {
			if leaked < 5 {
				t.Errorf("native tool name %q leaked into the generated data file — the (tool, native) table must not be emitted", e.Native)
			}
			leaked++
		}
	}
	if leaked > 5 {
		t.Errorf("... and %d more native names leaked", leaked-5)
	}
}

// TestNewTaxonomyTypesRenderSensibly pins the eight action types WP-T1
// introduced to close the measured `unknown` gap. They are the reason
// this generator exists: before it, the dashboard humanized them into
// gray "meta" chips because its hand-maintained registry had never heard
// of them.
func TestNewTaxonomyTypesRenderSensibly(t *testing.T) {
	d := decodeOrFail(t, generateOrFail(t))
	want := map[string]string{
		tooltax.ActionSubagentWait: tooltax.CategoryAgent,
		tooltax.ActionAgentMessage: tooltax.CategoryAgent,
		tooltax.ActionAgentControl: tooltax.CategoryAgent,
		tooltax.ActionStdinWrite:   tooltax.CategoryAgent,
		tooltax.ActionSkillInvoke:  tooltax.CategorySkill,
		tooltax.ActionSchedule:     tooltax.CategoryMeta,
		tooltax.ActionToolSearch:   tooltax.CategoryMeta,
		tooltax.ActionHarnessCall:  tooltax.CategoryMeta,
	}
	for at, category := range want {
		got, ok := d.ActionTypes[at]
		if !ok {
			t.Errorf("new action type %q is not in the generated registry", at)
			continue
		}
		if got.Category != category {
			t.Errorf("new action type %q has category %q, want %q", at, got.Category, category)
		}
		// A humanized fallback label would be the key with underscores
		// replaced; a real registry label is prose.
		if got.Label == "" || got.Label == strings.ReplaceAll(at, "_", " ") {
			t.Errorf("new action type %q has no real label (%q)", at, got.Label)
		}
	}
}

// TestSkillCategoryHasAColourVar — and every other category — closes the
// one hole the JSON mirror cannot close by itself: the per-category
// colour lives in CSS, which no TypeScript type checks. tooltax adding a
// category (as it did with "skill") must come with an --act-<category>
// var in BOTH themes, or that category renders as meta gray.
func TestSkillCategoryHasAColourVar(t *testing.T) {
	css, err := os.ReadFile(tokensPath)
	if err != nil {
		t.Fatalf("read %s: %v", tokensPath, err)
	}
	text := string(css)

	blocks := make(map[string]string, len(themeSelectors))
	for i, sel := range themeSelectors {
		start := strings.Index(text, sel)
		if start < 0 {
			t.Fatalf("%s: theme block %q not found — update themeSelectors", tokensPath, sel)
		}
		rest := text[start+len(sel):]
		end := strings.Index(rest, "\n}")
		if end < 0 {
			t.Fatalf("%s: theme block %q is unterminated", tokensPath, sel)
		}
		blocks[themeSelectors[i]] = rest[:end]
	}

	for _, category := range tooltax.Categories() {
		decl := "--act-" + category + ":"
		for sel, body := range blocks {
			if !strings.Contains(body, decl) {
				t.Errorf("%s: theme %q has no %s var — category %q would render as meta gray there",
					tokensPath, sel, decl, category)
			}
		}
	}
}

// ruleParse is a Go reference implementation of the emitted MCP rules,
// shaped like web/src/lib/actions.ts::parseMcpName.
//
// It is NOT the cross-language guarantee, and must not be described as
// one: it is a second GO implementation, so it can only prove that the
// emitted constants are sufficient to reproduce tooltax.MCPIdentity —
// reverting the TypeScript to its old behaviour would leave every test
// below green. The real parity gate compiles and RUNS actions.ts:
// scripts/verify-taxonomy-ts.sh over actiontax.vectors.gen.json
// (TestVectorsUseGoAsTheOracle pins the vectors themselves).
func ruleParse(rules mcpRules, raw string) (server, tool string, ok bool) {
	if !strings.HasPrefix(raw, rules.Prefix) {
		return "", "", false
	}
	rest := raw[len(rules.Prefix):]
	i := strings.Index(rest, rules.Separator)
	if i < rules.SeparatorMinIndex {
		return rest, "", true
	}
	return rest[:i], rest[i+len(rules.Separator):], true
}

// mcpCorpus covers the canonical form, both degenerate forms, the
// multi-separator case, non-MCP names and the colon/slash target forms.
var mcpCorpus = []string{
	"mcp__observer__get_file",
	"mcp__observer__get_session_summary",
	"mcp__ide__executeCode",
	"mcp__a__b__c",
	"mcp__server",
	"mcp__server__",
	"mcp__",
	"mcp____tool",
	"mcp_notaprefix",
	"Read",
	"",
	" mcp__a__b",
	"node_repl:js",
	"observer/get_file",
}

// TestMCPRulesReproduceGoParser is the parity proof for the emitted
// rules.
func TestMCPRulesReproduceGoParser(t *testing.T) {
	d := decodeOrFail(t, generateOrFail(t))
	for _, raw := range mcpCorpus {
		wantServer, wantTool, wantOK := tooltax.MCPIdentity(raw)
		server, tool, ok := ruleParse(d.MCP, raw)
		if server != wantServer || tool != wantTool || ok != wantOK {
			t.Errorf("ruleParse(%q) = (%q, %q, %v); tooltax.MCPIdentity gives (%q, %q, %v)",
				raw, server, tool, ok, wantServer, wantTool, wantOK)
		}
	}
}

// TestMCPDegenerateFormFollowsGo pins the exact case that used to
// diverge, with the expected values written out by hand (not derived
// from either implementation) so a change on EITHER side is loud.
func TestMCPDegenerateFormFollowsGo(t *testing.T) {
	d := decodeOrFail(t, generateOrFail(t))

	server, tool, ok := ruleParse(d.MCP, "mcp____tool")
	if server != "__tool" || tool != "" || !ok {
		t.Errorf("ruleParse(\"mcp____tool\") = (%q, %q, %v); want (\"__tool\", \"\", true) — "+
			"Go's behaviour, which WP-T2 aligned TypeScript onto", server, tool, ok)
	}

	// separatorMinIndex is what makes that true. Prove it is
	// load-bearing rather than incidental: relax it to 0 and the
	// degenerate name parses the OLD TypeScript way.
	relaxed := d.MCP
	relaxed.SeparatorMinIndex = 0
	if s, tl, _ := ruleParse(relaxed, "mcp____tool"); s != "" || tl != "tool" {
		t.Errorf("with separatorMinIndex=0, ruleParse(\"mcp____tool\") = (%q, %q); "+
			"want the pre-WP-T2 TypeScript answer (\"\", \"tool\") — "+
			"the constant is no longer the thing that decides", s, tl)
	}
}

// TestMCPRuleValuesMatchTooltax pins the emitted constants themselves.
func TestMCPRuleValuesMatchTooltax(t *testing.T) {
	d := decodeOrFail(t, generateOrFail(t))
	if d.MCP.Prefix != tooltax.MCPPrefix {
		t.Errorf("prefix = %q, want %q", d.MCP.Prefix, tooltax.MCPPrefix)
	}
	if d.MCP.Separator != tooltax.MCPSeparator {
		t.Errorf("separator = %q, want %q", d.MCP.Separator, tooltax.MCPSeparator)
	}
	if d.MCP.SeparatorMinIndex != tooltax.MCPSeparatorMinIndex {
		t.Errorf("separatorMinIndex = %d, want %d",
			d.MCP.SeparatorMinIndex, tooltax.MCPSeparatorMinIndex)
	}
	if d.MCP.TargetSeparator != tooltax.MCPTargetSeparator {
		t.Errorf("targetSeparator = %q, want %q", d.MCP.TargetSeparator, tooltax.MCPTargetSeparator)
	}
}

// TestWriteCreatesParentDir covers the gate's `-outdir /tmp/...` path.
func TestWriteCreatesParentDir(t *testing.T) {
	dir := t.TempDir()
	out := filepath.Join(dir, "nested", "actiontax.gen.json")
	data := generateOrFail(t)
	if err := write(out, data); err != nil {
		t.Fatalf("write: %v", err)
	}
	got, err := os.ReadFile(out)
	if err != nil {
		t.Fatalf("read back: %v", err)
	}
	if !bytes.Equal(got, data) {
		t.Error("written bytes differ from generated bytes")
	}
}

// TestTypesUnionMirrorsCategories pins the generated TypeScript union:
// exactly one member per canonical category, in tooltax's display order,
// and nothing invented locally. This union is what makes a missing
// colour a COMPILE error in actions.ts, so a union that silently lost a
// member would re-open the hole it exists to close.
func TestTypesUnionMirrorsCategories(t *testing.T) {
	src := generateTypesOrFail(t)

	if !strings.Contains(src, "DO NOT EDIT") {
		t.Error("generated .ts has no DO NOT EDIT marker")
	}
	if !strings.Contains(src, "export type ActionCategory =\n") {
		t.Fatalf("generated .ts does not declare ActionCategory:\n%s", src)
	}
	if !strings.HasSuffix(src, "\n") || strings.HasSuffix(src, "\n\n") {
		t.Error("generated .ts does not end with exactly one newline")
	}

	var members []string
	for _, line := range strings.Split(src, "\n") {
		if !strings.HasPrefix(line, "  | ") {
			continue
		}
		member := strings.TrimSuffix(strings.TrimPrefix(line, "  | "), ";")
		unquoted, err := strconv.Unquote(member)
		if err != nil {
			t.Fatalf("union member %q is not a quoted string: %v", member, err)
		}
		members = append(members, unquoted)
	}

	want := tooltax.Categories()
	if strings.Join(members, ",") != strings.Join(want, ",") {
		t.Errorf("union = [%s]; tooltax.Categories() = [%s]",
			strings.Join(members, ","), strings.Join(want, ","))
	}
	// Every member must be terminated correctly: only the last line
	// carries the semicolon, or tsc will not parse the file.
	if !strings.HasSuffix(strings.TrimRight(src, "\n"), strconv.Quote(want[len(want)-1])+";") {
		t.Errorf("union is not terminated with %q;\n%s", want[len(want)-1], src)
	}
}

// TestVectorsUseGoAsTheOracle is what makes the TypeScript gate a parity
// gate rather than a snapshot: every oracle=tooltax.MCPIdentity vector's
// expectation must be exactly what the Go parser returns for that row,
// recomputed here rather than trusted.
func TestVectorsUseGoAsTheOracle(t *testing.T) {
	v := generateVectorsOrFail(t)
	if len(v.Cases) == 0 {
		t.Fatal("no vectors emitted")
	}

	goCases := 0
	for _, c := range v.Cases {
		switch c.Oracle {
		case oracleGo:
			goCases++
			if c.Row.ActionType != nil {
				t.Errorf("%s: a Go-oracle vector must not set action_type — "+
					"the Go parser has no such input", c.Name)
			}
			if c.Row.Target != nil {
				t.Errorf("%s: a Go-oracle vector must not set target — "+
					"tooltax.MCPIdentity parses raw names only", c.Name)
			}
			if c.Row.RawToolName == nil {
				t.Errorf("%s: a Go-oracle vector must set raw_tool_name", c.Name)
				continue
			}
			server, tool, ok := tooltax.MCPIdentity(*c.Row.RawToolName)
			if !ok {
				if c.Want != nil {
					t.Errorf("%s: want %+v, but tooltax.MCPIdentity rejects the name",
						c.Name, *c.Want)
				}
				continue
			}
			if c.Want == nil {
				t.Errorf("%s: want null, but tooltax.MCPIdentity gives (%q, %q)",
					c.Name, server, tool)
				continue
			}
			if c.Want.Server != server || c.Want.Tool != tool {
				t.Errorf("%s: want (%q, %q); tooltax.MCPIdentity gives (%q, %q)",
					c.Name, c.Want.Server, c.Want.Tool, server, tool)
			}
		case oracleTSGuard:
			// No Go counterpart by construction — the expectation is the
			// declared contract for the TS-only path/URL guards. All we
			// can pin here is that it IS declared as such.
			if c.Row.ActionType == nil && c.Row.RawToolName == nil && c.Row.Target == nil {
				continue // the deliberate empty-row case
			}
		default:
			t.Errorf("%s: unknown oracle %q", c.Name, c.Oracle)
		}
	}
	if goCases == 0 {
		t.Error("no Go-oracle vectors — the TS gate would pin nothing that Go owns")
	}
}

// TestVectorsCoverTheKnownTraps pins the specific rows this gate exists
// for: the degenerate name that used to diverge, the colon form on both
// carriers, and the three path shapes finding 3 identified.
func TestVectorsCoverTheKnownTraps(t *testing.T) {
	v := generateVectorsOrFail(t)

	rawSeen := make(map[string]struct{})
	targetSeen := make(map[string]struct{})
	for _, c := range v.Cases {
		if c.Row.RawToolName != nil {
			rawSeen[*c.Row.RawToolName] = struct{}{}
		}
		if c.Row.Target != nil {
			targetSeen[*c.Row.Target] = struct{}{}
		}
	}
	for _, raw := range []string{"mcp____tool", "mcp__observer__get_file", "node_repl:js"} {
		if _, ok := rawSeen[raw]; !ok {
			t.Errorf("no vector carries raw_tool_name %q", raw)
		}
	}
	for _, target := range []string{
		`C:\repo\file.txt`,
		"C:/repo/file.txt",
		"/tmp/socket:query",
		"https://example.com/x",
		"observer:get_session_summary",
	} {
		if _, ok := targetSeen[target]; !ok {
			t.Errorf("no vector carries target %q", target)
		}
	}

	// The degenerate case must carry Go's answer, not the pre-WP-T2
	// TypeScript one — written out by hand so a change on EITHER side is
	// loud.
	for _, c := range v.Cases {
		if c.Row.RawToolName == nil || *c.Row.RawToolName != "mcp____tool" {
			continue
		}
		if c.Want == nil || c.Want.Server != "__tool" || c.Want.Tool != "" {
			t.Errorf("the mcp____tool vector expects %+v; want {__tool, \"\"} — "+
				"Go's behaviour, which WP-T2 aligned TypeScript onto", c.Want)
		}
	}
}

// TestProbeIsUnregistered keeps the fallback-category probe honest: if
// tooltax ever registered this key the emitted fallback would silently
// become that row's category.
func TestProbeIsUnregistered(t *testing.T) {
	if _, ok := tooltax.MetaForActionType(probeUnregistered); ok {
		t.Errorf("probe %q is a registered action type — pick another", probeUnregistered)
	}
}
