// Code generated by web/taxgen from internal/tooltax. DO NOT EDIT.
//
// Regenerate with `make taxonomy-build`; the `taxonomy-build-drift` CI job
// (`make verify-taxonomy-build`) fails until the regenerated file is
// committed.
//
// This file carries the TYPES; actiontax.gen.json carries the data. The
// split exists so that a category added on the Go side is a COMPILE
// error in the dashboards rather than a silent meta-gray chip:
// shared/lib/actions.ts keys its CATEGORY_COLOR map on ActionCategory,
// so a new member with no --act-<category> colour fails `npm run typecheck`.

/** The canonical action categories — tooltax.Categories(), in display
 * order (concrete work first, then coordination, then noise). */
export type ActionCategory =
  | "file"
  | "cmd"
  | "search"
  | "web"
  | "agent"
  | "skill"
  | "mcp"
  | "user"
  | "meta"
  | "fail";
