import {
  Anchor,
  Archive,
  ArchiveRestore,
  ArrowDownToLine,
  ArrowLeftRight,
  ArrowUpFromLine,
  BadgeCheck,
  Ban,
  Bot,
  BookOpen,
  Brain,
  Building2,
  CalendarDays,
  Calculator,
  CircleCheck,
  CircleDollarSign,
  CircleGauge,
  Clock,
  CloudDownload,
  Coins,
  Cpu,
  Crosshair,
  Crown,
  Database,
  DatabaseZap,
  Diff,
  DollarSign,
  DoorOpen,
  Eraser,
  FileCheck2,
  FileClock,
  FileCode2,
  FileJson,
  Files,
  FileText,
  Flame,
  FlaskConical,
  FoldVertical,
  Gavel,
  GitCommitHorizontal,
  Grid3x3,
  HandCoins,
  HardDrive,
  History,
  KeyRound,
  Layers,
  Lightbulb,
  Link,
  Link2Off,
  ListCollapse,
  ListFilter,
  ListOrdered,
  ListTodo,
  LockOpen,
  Logs,
  Maximize2,
  MessagesSquare,
  Minimize2,
  Package,
  PenLine,
  Percent,
  PiggyBank,
  Receipt,
  Repeat,
  Route,
  Scale,
  SearchCheck,
  Send,
  Server,
  ShieldCheck,
  Signpost,
  SlidersHorizontal,
  SquareChevronRight,
  Syringe,
  Table2,
  Tag,
  TrendingUp,
  Trash2,
  User,
  Wallet,
  Wrench,
  Zap,
  type LucideIcon,
} from "lucide-react";

// METRIC_ICONS: the ONE metric -> glyph table for every KPI tile in the node
// dashboard (StatCard / HeroStat / BigStat). Pages name the METRIC a tile
// shows, never a glyph, so the same metric carries the same icon on every
// page ("sessions" is MessagesSquare on Overview, Analysis, Compression and
// Cost alike) and two different metrics never share one (pinned by
// metricIcons.test.ts). Before this table the Coins / Bolt / Droplet /
// Sparkles glyphs were reused across unrelated tiles (Cache Read and Cache
// Write both Droplet, Output and Reasoning both Sparkles).
//
// A tile that shows the same metric over a different window or scope
// (Verdicts 24h / 7d, Mispredict rate / Anthropic mispredict rate) uses the
// same key on purpose: it is one metric, so it keeps one glyph.
//
// Shared by every app (moved from web/src/lib 2026-09-28) so a metric has the
// same glyph on the node dashboard, the org dashboard and the portal.
export const METRIC_ICONS = {
  // Spend and prices.
  spend: DollarSign,
  monthToDate: CalendarDays,
  budget: Wallet,
  burnRate: Flame,
  costPerTurn: Receipt,
  pricePerMOutput: Tag,
  nextTurnCost: TrendingUp,
  derivedCost: Calculator,
  summaryCost: CircleDollarSign,
  vendorReportedCost: BadgeCheck,
  drift: ArrowLeftRight,
  avoidableSpend: HandCoins,
  waste: Trash2,
  savings: PiggyBank,
  counterfactualSavings: FlaskConical,
  savingsUnlocked: LockOpen,
  netDelta: Diff,
  // Volume.
  sessions: MessagesSquare,
  actions: Zap,
  apiTurns: Repeat,
  tokenRows: FileJson,
  tokens: Coins,
  bytes: HardDrive,
  files: Files,
  commands: SquareChevronRight,
  commits: GitCommitHorizontal,
  aiCodeLines: FileCode2,
  tasks: ListTodo,
  // Token buckets.
  netInput: ArrowDownToLine,
  output: ArrowUpFromLine,
  reasoning: Brain,
  cacheRead: BookOpen,
  cacheWrite: PenLine,
  // Cache behaviour.
  cacheHitRate: DatabaseZap,
  cacheEvents: Logs,
  mispredictRate: Crosshair,
  prefixSurvival: Anchor,
  staleRereads: History,
  // Context and limits.
  contextWindow: Layers,
  highContext: Maximize2,
  limitSpent: CircleGauge,
  process: Cpu,
  // Models and tools.
  topModel: Bot,
  distinctTools: Wrench,
  busiestTool: Crown,
  successRate: CircleCheck,
  // Compression.
  compressionSavings: Minimize2,
  turnsCompressed: FoldVertical,
  stashes: Archive,
  retrievals: ArchiveRestore,
  retrieveRate: Percent,
  searchHits: SearchCheck,
  compactEvents: ListCollapse,
  injections: Syringe,
  rejectRate: Ban,
  summaryCalls: FileText,
  // Policy, guard and routing.
  guardPosture: ShieldCheck,
  verdicts: Gavel,
  auditChain: Link,
  auditChainBroken: Link2Off,
  policyMode: SlidersHorizontal,
  rules: ListFilter,
  admission: DoorOpen,
  egressRouting: Route,
  judge: Scale,
  routingDecisions: Signpost,
  calibrationCells: Grid3x3,
  openSuggestions: Lightbulb,
  benchmarkRuns: ListOrdered,
  latestRun: Clock,
  // Settings: cloud intelligence, enrolment, storage.
  consentReceipts: FileCheck2,
  liveReceipts: FileClock,
  outboxItems: Package,
  sendableNow: Send,
  syncedResults: CloudDownload,
  organisation: Building2,
  member: User,
  server: Server,
  credentialStore: KeyRound,
  databaseSize: Database,
  reclaimable: Eraser,
  tables: Table2,
} as const satisfies Record<string, LucideIcon>;

/** MetricKey names one KPI metric in {@link METRIC_ICONS}. */
export type MetricKey = keyof typeof METRIC_ICONS;

/** metricIcon returns the one glyph for a KPI metric. */
export function metricIcon(metric: MetricKey): LucideIcon {
  return METRIC_ICONS[metric];
}
