package pricingfeed

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"sort"
)

// CanonicalRows renders the deterministic signing/digest bytes for a feed's
// rows FROM THE DECODED TYPED ROWS.
//
// encoding/json's rendering IS the canonical form here, and that is a property
// of the SHAPE, not a hope — the same reasoning as orgcontract.canonicalPricingBody:
// Row has NO map anywhere, its (embedded) field order is fixed by the struct
// declaration, and the only ordering degree of freedom is the slice order,
// which this function pins by sorting on the model id. So a publisher that
// emits the rows in any order, and a verifier that decoded them in that order,
// sign and digest identical bytes.
//
// The *float64,omitempty rate fields keep this property across the nil-vs-
// quoted-zero distinction: a nil rate renders as nothing, a &0.0 renders as
// `0`, both deterministically — so a "not quoted" row and a "quoted free" row
// canonicalise to DIFFERENT bytes, which is exactly what they are.
//
// It does NOT mutate the caller's slice: it sorts a shallow copy.
//
// [Verify] prefers [canonicalRawRows] over this function whenever it has the
// envelope's raw received bytes (verify-over-received-bytes, docs/plans/
// peak-off-peak-pricing-plan-2026-09-20.md §3.4): this function necessarily
// drops any row field this build's Row/PricingPolicyRow/Economics structs
// don't declare, which is exactly the re-marshal freeze class that fix
// closes. CanonicalRows remains the signing-side and programmatic-envelope
// path (a publisher only ever has typed rows to sign).
func CanonicalRows(rows []Row) ([]byte, error) {
	sorted := make([]Row, len(rows))
	copy(sorted, rows)
	sort.SliceStable(sorted, func(i, j int) bool {
		return sorted[i].Model < sorted[j].Model
	})
	raw, err := json.Marshal(sorted)
	if err != nil {
		return nil, fmt.Errorf("pricingfeed.CanonicalRows: %w", err)
	}
	return raw, nil
}

// Digest is the sha256 hex of CanonicalRows(rows) — the envelope's Digest field
// and the ETag substrate (§A). Hashing the CANONICAL rows (not the received
// byte order) means two publishes of the same prices in a different row order
// share a digest, so the node's If-None-Match short-circuits correctly.
func Digest(rows []Row) (string, error) {
	canonical, err := CanonicalRows(rows)
	if err != nil {
		return "", err
	}
	return digestOf(canonical), nil
}

// digestOf is the sha256 hex of already-canonicalised bytes. Verify uses it to
// avoid re-marshaling the rows a second time after it has the canonical form.
func digestOf(canonical []byte) string {
	sum := sha256.Sum256(canonical)
	return hex.EncodeToString(sum[:])
}

// canonicalRawRows renders the deterministic signing/digest bytes for a
// feed's rows FROM THE RAW RECEIVED "rows" JSON ARRAY BYTES (Envelope's
// unexported rawRows, captured by UnmarshalJSON), rather than from the
// decoded typed []Row. It reproduces [CanonicalRows]'s two degrees of
// freedom it must pin — element order and insignificant whitespace/encoding
// — but does so WITHOUT going through the typed Row struct, so a field
// neither Row nor its embedded PricingPolicyRow/Economics know about (e.g. a
// future nested nested "peak" object) rides along in the canonical bytes
// instead of being silently dropped.
//
// Per element: json.Compact removes only insignificant whitespace (it does
// not reorder keys or reformat numbers), and a narrow decode into
// struct{ Model string } recovers the sort key without touching the rest of
// the element. Elements are then stable-sorted by that key — the same
// ordering CanonicalRows applies — and joined into a JSON array.
//
// Byte-identity with CanonicalRows(typedRows) holds whenever every row's raw
// bytes were themselves produced by encoding/json (the signer's own
// json.Marshal, or a re-marshal of a fully-decoded envelope): encoding/json
// already emits compact, key-order-fixed, canonically-formatted numbers, so
// json.Compact of such bytes is a no-op and the two functions rebuild the
// same document (pinned by TestCanonicalRawRowsMatchesTypedForNoUnknownFields).
// A HAND-WRITTEN body with reordered keys or non-canonical number spelling
// (e.g. "1.50" vs "1.5") would NOT byte-match — that is an accepted, narrow
// residual (docs/plans/peak-off-peak-pricing-plan-2026-09-20.md §3.4): every
// real feed body in the wild is machine-generated by encoding/json on the
// signer side, never hand-authored.
func canonicalRawRows(raw []byte) ([]byte, error) {
	var elems []json.RawMessage
	if err := json.Unmarshal(raw, &elems); err != nil {
		return nil, fmt.Errorf("pricingfeed.canonicalRawRows: unmarshal rows array: %w", err)
	}
	type keyed struct {
		model   string
		compact []byte
	}
	out := make([]keyed, 0, len(elems))
	for i, elem := range elems {
		var compacted bytes.Buffer
		if err := json.Compact(&compacted, elem); err != nil {
			return nil, fmt.Errorf("pricingfeed.canonicalRawRows: compact row %d: %w", i, err)
		}
		var mk struct {
			Model string `json:"model"`
		}
		if err := json.Unmarshal(elem, &mk); err != nil {
			return nil, fmt.Errorf("pricingfeed.canonicalRawRows: read model key of row %d: %w", i, err)
		}
		out = append(out, keyed{model: mk.Model, compact: compacted.Bytes()})
	}
	sort.SliceStable(out, func(i, j int) bool {
		return out[i].model < out[j].model
	})

	var buf bytes.Buffer
	buf.WriteByte('[')
	for i, k := range out {
		if i > 0 {
			buf.WriteByte(',')
		}
		buf.Write(k.compact)
	}
	buf.WriteByte(']')
	return buf.Bytes(), nil
}
