// EmptyIllustration — the empty-state art set. GENERATED by
// design/brand-icons/build-illustrations.mjs; edit that, not this file. Pure, no
// fetch/state. Colours come from theme tokens via illustrations.css, so the
// same art works in light and dark. The grid ids are made unique per
// instance with useId() so several illustrations can share a page.
import { useId, type ReactNode } from "react";

export type IllustrationKind =
  | "sessions"
  | "chart"
  | "search"
  | "all-clear"
  | "locked"
  | "offline"
  | "connect"
  | "inbox"
  | "error"
  | "enrich"
  | "cohort"
  | "setup";

export function EmptyIllustration({
  kind,
  size = 160,
  className,
}: {
  kind: IllustrationKind;
  size?: number;
  className?: string;
}) {
  const uid = useId().replace(/:/g, "");
  return (
    <svg
      className={["sb-ill", className].filter(Boolean).join(" ")}
      width={size}
      height={(size * 3) / 4}
      viewBox="0 0 160 120"
      aria-hidden
    >
      <defs>
        <pattern id={`g${uid}`} width="10" height="10" patternUnits="userSpaceOnUse">
          <circle cx="1" cy="1" r=".9" className="g" />
        </pattern>
        <radialGradient id={`f${uid}`} cx="50%" cy="55%" r="60%">
          <stop offset="0" stopColor="#fff" stopOpacity=".9" />
          <stop offset="1" stopColor="#fff" stopOpacity="0" />
        </radialGradient>
        <mask id={`m${uid}`}>
          <rect width="160" height="120" fill={`url(#f${uid})`} />
        </mask>
      </defs>
      <rect width="160" height="120" fill={`url(#g${uid})`} mask={`url(#m${uid})`} />
      {ART[kind]}
    </svg>
  );
}

/** Suggested default copy per kind (callers usually override). */
export const ILLUSTRATION_TITLES: Record<IllustrationKind, string> = {
  "sessions": "No sessions yet",
  "chart": "No data in this range",
  "search": "No matches",
  "all-clear": "All clear",
  "locked": "You don't have access",
  "offline": "Can't reach the daemon",
  "connect": "Connect to your org",
  "inbox": "Nothing waiting",
  "error": "Something went wrong",
  "enrich": "No enriched sessions yet",
  "cohort": "Not enough people yet",
  "setup": "Finish setting up",
};

const ART: Record<IllustrationKind, ReactNode> = {
  // Sessions / Live / Overview first run: waiting for the first captured session
  "sessions": (
    <>
      <rect className="p" x="28" y="26" width="104" height="70" rx="8"/>
      <path className="l" d="M28 40h104"/>
      <circle className="m" cx="38" cy="33" r="2"/><circle className="m" cx="45" cy="33" r="2"/><circle className="m" cx="52" cy="33" r="2"/>
      <path className="la" d="M40 55l6 5-6 5"/>
      <rect className="a2 sb-caret" x="52" y="62" width="9" height="3" rx="1"/>
      <path className="l2" d="M40 78h52M40 86h34"/>
      <g className="sb-float"><rect className="a" x="127" y="10" width="9" height="9" rx="2"/></g><g className="sb-float sb-float-delay"><rect className="a" x="118" y="19" width="9" height="9" rx="2"/></g>
    </>
  ),
  // ChartState empty: every chart card (Cost, Tokens, Cache, Analysis, org Overview)
  "chart": (
    <>
      <path className="l" d="M30 20v72h104"/>
      <rect className="ghost" x="44" y="60" width="12" height="32" rx="2"/>
      <rect className="ghost" x="64" y="48" width="12" height="44" rx="2"/>
      <rect className="ghost" x="84" y="68" width="12" height="24" rx="2"/>
      <rect className="ghost" x="104" y="54" width="12" height="38" rx="2"/>
      <path className="la sb-dash-flow" d="M36 80h92"/>
      <g className="sb-float"><rect className="a" x="124" y="12" width="8" height="8" rx="2"/></g><g className="sb-float sb-float-delay"><rect className="a" x="116" y="20" width="8" height="8" rx="2"/></g>
    </>
  ),
  // Search, filtered tables, command palette, EntityMultiPicker with no hits
  "search": (
    <>
      <rect className="p" x="30" y="26" width="72" height="66" rx="7"/>
      <path className="l2" d="M42 42h46M42 53h38M42 64h30M42 75h40"/>
      <circle className="p2" cx="104" cy="70" r="18"/>
      <path className="lt" d="M117 83l13 13"/>
      <path className="l" d="M97 70h14"/>
      <g className="sb-float"><rect className="a" x="130" y="12" width="8" height="8" rx="2"/></g><g className="sb-float sb-float-delay"><rect className="a" x="122" y="20" width="8" height="8" rx="2"/></g>
    </>
  ),
  // Alerts, guard findings, security, audit anomalies, budget breaches: nothing firing
  "all-clear": (
    <>
      <path className="p" d="M80 18l30 11v28c0 19-12 32-30 40-18-8-30-21-30-40V29z"/>
      <path className="ok sb-draw-check" pathLength={1} d="M67 57l9 9 18-19"/>
      <path className="l2" d="M38 38v6M35 41h6M124 72v6M121 75h6M122 30v4M120 32h4"/>
      <g className="sb-float"><rect className="a" x="134" y="14" width="8" height="8" rx="2"/></g><g className="sb-float sb-float-delay"><rect className="a" x="126" y="22" width="8" height="8" rx="2"/></g>
    </>
  ),
  // RBAC read-only / permission denied (web2), consent not granted (webcloud)
  "locked": (
    <>
      <rect className="p" x="34" y="28" width="92" height="62" rx="8"/>
      <path className="l2" d="M46 42h30M46 50h22M100 42h14"/>
      <path className="l" d="M70 58v-7a10 10 0 0120 0v7"/>
      <rect className="p2" x="62" y="57" width="36" height="27" rx="5"/>
      <circle className="m" cx="80" cy="68" r="3"/><path className="l" d="M80 70v6"/>
      <g className="sb-float"><rect className="a" x="132" y="10" width="8" height="8" rx="2"/></g><g className="sb-float sb-float-delay"><rect className="a" x="124" y="18" width="8" height="8" rx="2"/></g>
    </>
  ),
  // Dashboard lost the local daemon / org server unreachable / cloud API down
  "offline": (
    <>
      <path className="l" d="M16 70h36"/>
      <rect className="p" x="52" y="61" width="18" height="18" rx="3"/>
      <path className="l" d="M70 66h7M70 74h7"/>
      <path className="warn" d="M86 58l5 6-5 5 5 6"/>
      <rect className="p" x="98" y="57" width="20" height="26" rx="4"/>
      <rect className="m" x="103" y="64" width="3" height="5" rx="1"/><rect className="m" x="110" y="64" width="3" height="5" rx="1"/>
      <path className="l" d="M118 70h26"/>
      <g className="sb-float"><rect className="a" x="28" y="22" width="8" height="8" rx="2"/></g><g className="sb-float sb-float-delay"><rect className="a" x="20" y="30" width="8" height="8" rx="2"/></g>
    </>
  ),
  // Node not enrolled / org sign-in / cloud sign-in empty states
  "connect": (
    <>
      <rect className="p" x="20" y="46" width="40" height="28" rx="5"/>
      <path className="l" d="M15 80h50"/>
      <path className="la sb-dash-flow" d="M62 60c14 0 26 0 40 0"/>
      <rect className="p" x="104" y="36" width="36" height="46" rx="6"/>
      <path className="l2" d="M112 48h20M112 58h20M112 68h20"/>
      <circle className="okf" cx="133" cy="76" r="2"/>
      <g className="sb-float"><rect className="a" x="82" y="34" width="8" height="8" rx="2"/></g><g className="sb-float sb-float-delay"><rect className="a" x="74" y="42" width="8" height="8" rx="2"/></g>
    </>
  ),
  // Approvals inbox (assistant proposals), pending members, pending grants
  "inbox": (
    <>
      <path className="p" d="M40 66l10-24h60l10 24v22a6 6 0 01-6 6H46a6 6 0 01-6-6z"/>
      <path className="l" d="M40 66h22l6 10h24l6-10h22"/>
      <circle className="okbg" cx="80" cy="28" r="12"/>
      <path className="ok sb-draw-check" pathLength={1} d="M74 28l4 4 8-8"/>
      <g className="sb-float"><rect className="a" x="132" y="14" width="8" height="8" rx="2"/></g><g className="sb-float sb-float-delay"><rect className="a" x="124" y="22" width="8" height="8" rx="2"/></g>
    </>
  ),
  // ChartState / ErrorPanel / LoadState errors (with a Try again action)
  "error": (
    <>
      <rect className="p" x="34" y="30" width="92" height="60" rx="8"/>
      <path className="warnbg" d="M80 42l21 37H59z"/>
      <path className="warn" d="M80 55v12"/><circle className="warnf" cx="80" cy="73" r="2"/>
      <g className="sb-float"><rect className="a" x="132" y="12" width="8" height="8" rx="2"/></g><g className="sb-float sb-float-delay"><rect className="a" x="124" y="20" width="8" height="8" rx="2"/></g>
    </>
  ),
  // webcloud Sessions / Overview first run, session-detail Intelligence tab before a run
  "enrich": (
    <>
      <rect className="p" x="30" y="32" width="84" height="58" rx="8"/>
      <path className="l2" d="M42 48h44M42 58h56M42 68h36M42 78h48"/>
      <g className="sb-float"><path className="a2f" d="M118 30l3.5 9 9 3.5-9 3.5-3.5 9-3.5-9-9-3.5 9-3.5z"/></g>
      <g className="sb-float sb-float-delay"><path className="a2f" d="M134 58l2 5 5 2-5 2-2 5-2-5-5-2 5-2z"/></g>
      <g className="sb-float"><rect className="a" x="27" y="10" width="7" height="7" rx="2"/></g><g className="sb-float sb-float-delay"><rect className="a" x="20" y="17" width="7" height="7" rx="2"/></g>
    </>
  ),
  // webcloud Community k-anonymity floor (below 30 members), small-team org rollups
  "cohort": (
    <>
      <circle className="a" cx="35" cy="44" r="3.2"/><circle className="a" cx="45" cy="44" r="3.2"/><circle className="a" cx="55" cy="44" r="3.2"/><circle className="a" cx="65" cy="44" r="3.2"/><circle className="a" cx="75" cy="44" r="3.2"/><circle className="a" cx="85" cy="44" r="3.2"/><circle className="a" cx="95" cy="44" r="3.2"/><circle className="ghostc" cx="105" cy="44" r="3.2"/><circle className="ghostc" cx="115" cy="44" r="3.2"/><circle className="ghostc" cx="125" cy="44" r="3.2"/><circle className="ghostc" cx="35" cy="58" r="3.2"/><circle className="ghostc" cx="45" cy="58" r="3.2"/><circle className="ghostc" cx="55" cy="58" r="3.2"/><circle className="ghostc" cx="65" cy="58" r="3.2"/><circle className="ghostc" cx="75" cy="58" r="3.2"/><circle className="ghostc" cx="85" cy="58" r="3.2"/><circle className="ghostc" cx="95" cy="58" r="3.2"/><circle className="ghostc" cx="105" cy="58" r="3.2"/><circle className="ghostc" cx="115" cy="58" r="3.2"/><circle className="ghostc" cx="125" cy="58" r="3.2"/><circle className="ghostc" cx="35" cy="72" r="3.2"/><circle className="ghostc" cx="45" cy="72" r="3.2"/><circle className="ghostc" cx="55" cy="72" r="3.2"/><circle className="ghostc" cx="65" cy="72" r="3.2"/><circle className="ghostc" cx="75" cy="72" r="3.2"/><circle className="ghostc" cx="85" cy="72" r="3.2"/><circle className="ghostc" cx="95" cy="72" r="3.2"/><circle className="ghostc" cx="105" cy="72" r="3.2"/><circle className="ghostc" cx="115" cy="72" r="3.2"/><circle className="ghostc" cx="125" cy="72" r="3.2"/>
      <path className="la" d="M30 88h100" strokeDasharray="3 4"/>
      <g className="sb-float"><rect className="a" x="133" y="14" width="7" height="7" rx="2"/></g><g className="sb-float sb-float-delay"><rect className="a" x="126" y="21" width="7" height="7" rx="2"/></g>
    </>
  ),
  // First-run checklists (init / hooks / proxy route / enrol), setup wizard steps
  "setup": (
    <>
      <rect className="p" x="42" y="20" width="76" height="80" rx="8"/>
      <rect className="okbg" x="52" y="34" width="11" height="11" rx="3"/><path className="ok" d="M54.5 39.5l2.5 2.5 4-4.5"/>
      <rect className="okbg" x="52" y="54" width="11" height="11" rx="3"/><path className="ok" d="M54.5 59.5l2.5 2.5 4-4.5"/>
      <rect className="todo" x="52" y="74" width="11" height="11" rx="3"/>
      <path className="l2" d="M70 39.5h36M70 59.5h28M70 79.5h32"/>
      <g className="sb-float"><rect className="a" x="128" y="8" width="8" height="8" rx="2"/></g><g className="sb-float sb-float-delay"><rect className="a" x="120" y="16" width="8" height="8" rx="2"/></g>
    </>
  ),
};
