// Unit tests for the pure helpers in src/binary-internals.ts.
//
// Kept separate from src/binary.ts so we don't need a `vscode`
// runtime shim — `vscode` is only imported by binary.ts itself, and
// resolveBinary / downloadFromReleases are exercised manually in the
// Extension Development Host (M0 acceptance §4 of the plan).

import { test, describe } from 'node:test';
import assert from 'node:assert/strict';
import * as os from 'node:os';
import * as path from 'node:path';
import * as fs from 'node:fs/promises';
import {
  PLATFORM_TO_ASSET,
  evaluateCachedBinary,
  exeName,
  parseSha256Sums,
  which,
  fileExists,
  isExecutableFile,
  probeVersion,
  resolveLocalBinary,
  type VersionProbe,
} from '../../src/binary-internals';

describe('parseSha256Sums', () => {
  const sample = [
    '# generated by sha256sum',
    '',
    '0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef  observer-v1.7.26-linux-x64.tar.gz',
    'fedcba9876543210fedcba9876543210fedcba9876543210fedcba9876543210  observer-v1.7.26-darwin-arm64.tar.gz',
    'aaaabbbbccccddddeeeeffff0000111122223333444455556666777788889999 *observer-v1.7.26-win32-x64.zip',
    '',
  ].join('\n');

  test('extracts hash for an existing filename', () => {
    assert.equal(
      parseSha256Sums(sample, 'observer-v1.7.26-linux-x64.tar.gz'),
      '0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef',
    );
  });

  test('matches the asterisk-prefix (binary mode) format', () => {
    assert.equal(
      parseSha256Sums(sample, 'observer-v1.7.26-win32-x64.zip'),
      'aaaabbbbccccddddeeeeffff0000111122223333444455556666777788889999',
    );
  });

  test('returns undefined for a missing filename', () => {
    assert.equal(parseSha256Sums(sample, 'nonexistent.tar.gz'), undefined);
  });

  test('skips comments and blank lines', () => {
    const noisy = '# header\n\n# another comment\n';
    assert.equal(parseSha256Sums(noisy, 'whatever.tar.gz'), undefined);
  });

  test('handles CRLF line endings (Windows SHA256SUMS)', () => {
    const crlf = sample.replace(/\n/g, '\r\n');
    assert.equal(
      parseSha256Sums(crlf, 'observer-v1.7.26-darwin-arm64.tar.gz'),
      'fedcba9876543210fedcba9876543210fedcba9876543210fedcba9876543210',
    );
  });

  test('lowercases mixed-case hex from the input', () => {
    const upper =
      '0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF  archive.tar.gz';
    assert.equal(
      parseSha256Sums(upper, 'archive.tar.gz'),
      '0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef',
    );
  });
});

describe('PLATFORM_TO_ASSET', () => {
  test('covers the five matrix-built platforms', () => {
    const expected = new Set([
      'linux-x64',
      'linux-arm64',
      'darwin-x64',
      'darwin-arm64',
      'win32-x64',
    ]);
    assert.deepEqual(new Set(Object.keys(PLATFORM_TO_ASSET)), expected);
  });

  test('asset name equals the key (no aliasing)', () => {
    for (const [k, v] of Object.entries(PLATFORM_TO_ASSET)) {
      assert.equal(k, v, `expected ${k} to map to itself`);
    }
  });
});

describe('exeName', () => {
  test('matches the host platform', () => {
    assert.equal(
      exeName(),
      process.platform === 'win32' ? 'observer.exe' : 'observer',
    );
  });
});

describe('which', () => {
  test('returns undefined when PATH is empty', async () => {
    assert.equal(await which('observer', { PATH: '' }), undefined);
  });

  test('returns undefined when the command is not on any PATH dir', async () => {
    const tmp = await fs.mkdtemp(path.join(os.tmpdir(), 'observer-which-'));
    try {
      assert.equal(await which('definitely-not-on-path', { PATH: tmp }), undefined);
    } finally {
      await fs.rm(tmp, { recursive: true, force: true });
    }
  });

  test('finds an executable in a PATH directory', async () => {
    if (process.platform === 'win32') return; // skip — PATHEXT path covered separately
    const tmp = await fs.mkdtemp(path.join(os.tmpdir(), 'observer-which-'));
    try {
      const target = path.join(tmp, 'fake-observer');
      await fs.writeFile(target, '#!/bin/sh\necho hi\n', { mode: 0o755 });
      const found = await which('fake-observer', { PATH: tmp });
      assert.equal(found, target);
      assert.ok(await fileExists(found!));
    } finally {
      await fs.rm(tmp, { recursive: true, force: true });
    }
  });

  test('skips empty PATH segments', async () => {
    const tmp = await fs.mkdtemp(path.join(os.tmpdir(), 'observer-which-'));
    try {
      const target = path.join(tmp, 'tool');
      await fs.writeFile(target, '#!/bin/sh\n', { mode: 0o755 });
      // Empty segments around the real dir; `which` should not crash.
      const PATH = [`${path.delimiter}`, tmp, ''].join(path.delimiter);
      const found = await which('tool', { PATH });
      assert.equal(found, target);
    } finally {
      await fs.rm(tmp, { recursive: true, force: true });
    }
  });

  test('parallel probe: lowest-index hit wins even when a later dir resolves first', async () => {
    // Two PATH dirs both "contain" the binary. The LATER dir's fs probe
    // resolves first (faster), but PATH precedence must still return the
    // earlier dir. This only passes if all candidates are probed concurrently
    // and the result is chosen by index, not by which promise settled first.
    const dirA = path.join('/fake', 'a');
    const dirB = path.join('/fake', 'b');
    const first = path.join(dirA, 'observer');
    const second = path.join(dirB, 'observer');
    const order: string[] = [];
    const exists = (p: string): Promise<boolean> =>
      new Promise((resolve) => {
        const present = p === first || p === second;
        // Make the EARLIER-index candidate slower to settle.
        const delay = p === first ? 20 : 1;
        setTimeout(() => {
          order.push(p);
          resolve(present);
        }, delay);
      });
    const found = await which('observer', { PATH: [dirA, dirB].join(path.delimiter) }, exists);
    assert.equal(found, first, 'lowest-index PATH dir must win');
    // Sanity: the later candidate really did settle before the earlier one,
    // proving the probes ran concurrently rather than short-circuiting.
    assert.equal(order[0], second, 'expected concurrent probing (fast one first)');
  });

  test('parallel probe: returns undefined when no candidate exists', async () => {
    const exists = (): Promise<boolean> => Promise.resolve(false);
    const found = await which(
      'observer',
      { PATH: ['/x/a', '/x/b', '/x/c'].join(path.delimiter) },
      exists,
    );
    assert.equal(found, undefined);
  });
});

describe('isExecutableFile', () => {
  test('accepts a regular executable file, rejects directory & non-exec', async () => {
    const tmp = await fs.mkdtemp(path.join(os.tmpdir(), 'observer-exec-'));
    try {
      const dir = path.join(tmp, 'a-dir');
      await fs.mkdir(dir);
      const execFile = path.join(tmp, 'good');
      await fs.writeFile(execFile, '#!/bin/sh\n', { mode: 0o755 });
      const plainFile = path.join(tmp, 'plain.txt');
      await fs.writeFile(plainFile, 'not a binary', { mode: 0o644 });

      // A directory is never an acceptable binary, on any platform.
      assert.equal(await isExecutableFile(dir), false, 'directory must be rejected');
      // A missing path is rejected.
      assert.equal(await isExecutableFile(path.join(tmp, 'nope')), false);
      // A real executable file is accepted.
      assert.equal(await isExecutableFile(execFile), true, 'executable file must be accepted');
      if (process.platform !== 'win32') {
        // On POSIX the execute bit is required; on Windows it is meaningless.
        assert.equal(await isExecutableFile(plainFile), false, 'non-exec file must be rejected on POSIX');
      }
    } finally {
      await fs.rm(tmp, { recursive: true, force: true });
    }
  });
});

describe('probeVersion', () => {
  test('ok:false when the binary cannot be executed', async () => {
    // A path that does not exist → spawn error (ENOENT) → rejection signal.
    const res = await probeVersion(path.join(os.tmpdir(), 'observer-does-not-exist-xyz'));
    assert.equal(res.ok, false);
    assert.equal(res.version, 'unknown');
    assert.ok(res.error, 'a rejected probe carries an error message');
  });

  test('ok:false when the target is not an executable program (ENOEXEC/EACCES)', async () => {
    if (process.platform === 'win32') return; // exec semantics differ on Windows
    const tmp = await fs.mkdtemp(path.join(os.tmpdir(), 'observer-probe-'));
    try {
      const garbage = path.join(tmp, 'observer');
      // Executable bit set but the content is not a runnable program.
      await fs.writeFile(garbage, 'this is not a binary\x00\x01\x02', { mode: 0o755 });
      const res = await probeVersion(garbage);
      assert.equal(res.ok, false, 'a corrupt/non-program file must report ok:false');
    } finally {
      await fs.rm(tmp, { recursive: true, force: true });
    }
  });
});

describe('evaluateCachedBinary', () => {
  const binPath = path.join('/cache', 'v1.2.3', 'observer');
  const sentinelPath = path.join('/cache', 'v1.2.3', '.version');
  const expectedVersion = '1.2.3';

  const alwaysOk: (p: string) => Promise<VersionProbe> = async () => ({
    ok: true,
    version: expectedVersion,
  });
  const alwaysExec = async (): Promise<boolean> => true;

  test('healthy cached binary (sentinel matches, exec, runs) → reuse', async () => {
    const d = await evaluateCachedBinary({
      binPath,
      sentinelPath,
      expectedVersion,
      isExecutableFile: alwaysExec,
      readFileSafe: async () => expectedVersion,
      probeVersion: alwaysOk,
    });
    assert.equal(d.reuse, true);
    assert.equal(d.version, expectedVersion);
    assert.equal(d.reason, undefined);
  });

  test('sentinel version mismatch → reject (no probe needed)', async () => {
    let probed = false;
    const d = await evaluateCachedBinary({
      binPath,
      sentinelPath,
      expectedVersion,
      isExecutableFile: alwaysExec,
      readFileSafe: async () => '1.1.0', // stale sentinel
      probeVersion: async () => {
        probed = true;
        return { ok: true, version: '1.1.0' };
      },
    });
    assert.equal(d.reuse, false);
    assert.match(d.reason!, /sentinel version 1\.1\.0 != 1\.2\.3/);
    assert.equal(probed, false, 'a mismatched sentinel short-circuits before probing');
  });

  test('missing sentinel → reject', async () => {
    const d = await evaluateCachedBinary({
      binPath,
      sentinelPath,
      expectedVersion,
      isExecutableFile: alwaysExec,
      readFileSafe: async () => undefined, // no sentinel file
      probeVersion: alwaysOk,
    });
    assert.equal(d.reuse, false);
    assert.match(d.reason!, /\(none\) != 1\.2\.3/);
  });

  // The core MED regression: sentinel matches but the cached path is a
  // directory / non-executable → must be rejected (old code reused it forever).
  test('corrupt cache: sentinel matches but path is not an executable file → reject', async () => {
    let probed = false;
    const d = await evaluateCachedBinary({
      binPath,
      sentinelPath,
      expectedVersion,
      isExecutableFile: async () => false, // directory / non-exec / missing
      readFileSafe: async () => expectedVersion, // sentinel says it's the right version
      probeVersion: async () => {
        probed = true;
        return { ok: true, version: expectedVersion };
      },
    });
    assert.equal(d.reuse, false, 'a non-executable cached binary must NOT be reused');
    assert.match(d.reason!, /is not an executable file/);
    assert.equal(probed, false, 'no point probing --version on a non-executable file');
  });

  // Sentinel matches, it's an executable file, but --version cannot run
  // (corrupt/truncated download) → reject so the caller re-downloads.
  test('corrupt cache: executable file but --version fails → reject', async () => {
    const d = await evaluateCachedBinary({
      binPath,
      sentinelPath,
      expectedVersion,
      isExecutableFile: alwaysExec,
      readFileSafe: async () => expectedVersion,
      probeVersion: async () => ({ ok: false, version: 'unknown', error: 'exec ENOEXEC' }),
    });
    assert.equal(d.reuse, false, 'a cached binary that cannot run must NOT be reused');
    assert.match(d.reason!, /--version failed/);
    assert.match(d.reason!, /ENOEXEC/);
  });
});

describe('resolveLocalBinary', () => {
  const bundledPath = path.join('/ext', 'bin', 'observer');
  const settingPath = path.join('/custom', 'observer');
  const pathHit = path.join('/usr/local/bin', 'observer');

  // Version probes for the fake layer: `ok` binaries report a version, and by
  // default any path is a healthy binary. Individual tests override to model a
  // corrupt/unspawnable candidate.
  const okVersion = (version: string): ((p: string) => Promise<VersionProbe>) => {
    return async () => ({ ok: true, version });
  };
  const alwaysOk: (p: string) => Promise<VersionProbe> = okVersion('9.9.9');

  test('explicit setting wins over everything (carrying its version)', async () => {
    const res = await resolveLocalBinary({
      settingPath,
      bundledPath,
      preferPathBinary: false,
      fileExists: async (p) => p === settingPath || p === bundledPath,
      which: async () => pathHit,
      probeVersion: alwaysOk,
    });
    assert.deepEqual(res, { hit: { path: settingPath, source: 'setting', version: '9.9.9' } });
  });

  test('bundled binary is preferred over PATH by default (GitHub #5)', async () => {
    let whichCalled = false;
    const res = await resolveLocalBinary({
      bundledPath,
      preferPathBinary: false,
      fileExists: async (p) => p === bundledPath,
      which: async () => {
        whichCalled = true;
        return pathHit;
      },
      probeVersion: alwaysOk,
    });
    assert.deepEqual(res.hit, { path: bundledPath, source: 'bundled', version: '9.9.9' });
    // The bundled binary still WINS, which is what GitHub #5 asked for. What
    // changed with the O7 guard (enterprise update management, plan §6 O7) is
    // that PATH is now probed once afterwards, to find out whether the
    // installed daemon has self-updated past the bundled copy. Here it has not
    // (no PATH candidate passes fileExists), so the bundled hit stands.
    //
    // The cost is bounded to that comparison: the probe runs only when the
    // bundled copy won, and only to answer "is the installed one newer".
    // Without it, an extension pinned to release N would relaunch its own
    // older binary over a node that just updated itself to N+1.
    assert.equal(whichCalled, true, 'PATH is probed once so the O7 guard can compare versions');
  });

  test('preferPathBinary=true restores PATH-first order', async () => {
    const res = await resolveLocalBinary({
      bundledPath,
      preferPathBinary: true,
      // bundled also present; the PATH hit is (as `which` guarantees) a file too.
      fileExists: async (p) => p === bundledPath || p === pathHit,
      which: async () => pathHit,
      probeVersion: alwaysOk,
    });
    assert.deepEqual(res.hit, { path: pathHit, source: 'path', version: '9.9.9' });
  });

  test('falls back to PATH when the bundled binary is absent', async () => {
    const res = await resolveLocalBinary({
      bundledPath,
      preferPathBinary: false,
      fileExists: async (p) => p === pathHit, // no bundled binary; only the PATH hit
      which: async () => pathHit,
      probeVersion: alwaysOk,
    });
    assert.deepEqual(res.hit, { path: pathHit, source: 'path', version: '9.9.9' });
  });

  test('falls back to bundled when preferPathBinary=true but PATH is empty', async () => {
    const res = await resolveLocalBinary({
      bundledPath,
      preferPathBinary: true,
      fileExists: async (p) => p === bundledPath,
      which: async () => undefined,
      probeVersion: alwaysOk,
    });
    assert.deepEqual(res.hit, { path: bundledPath, source: 'bundled', version: '9.9.9' });
  });

  test('ignores an empty setting path', async () => {
    const res = await resolveLocalBinary({
      settingPath: '',
      bundledPath,
      preferPathBinary: false,
      fileExists: async (p) => p === bundledPath,
      which: async () => undefined,
      probeVersion: alwaysOk,
    });
    assert.deepEqual(res.hit, { path: bundledPath, source: 'bundled', version: '9.9.9' });
    assert.equal(res.settingError, undefined, 'an empty setting is not an error');
  });

  test('ignores a setting path that does not exist on disk', async () => {
    const res = await resolveLocalBinary({
      settingPath,
      bundledPath,
      preferPathBinary: false,
      fileExists: async (p) => p === bundledPath, // setting path missing
      which: async () => undefined,
      probeVersion: alwaysOk,
    });
    assert.deepEqual(res.hit, { path: bundledPath, source: 'bundled', version: '9.9.9' });
    assert.ok(res.settingError, 'a configured-but-missing setting is reported');
    assert.match(res.settingError!, new RegExp(settingPath.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')));
  });

  // MED regression (a): observer.binary.path pointing at a directory / garbage
  // must NOT win permanently — it is rejected, the bundled binary wins, and the
  // bad path is surfaced by name so the user can fix their setting.
  test('directory-at-setting-path is rejected → bundled wins + error surfaced', async () => {
    const res = await resolveLocalBinary({
      settingPath, // exists on disk but is a directory → fileExists(isExecutableFile) says false
      bundledPath,
      preferPathBinary: false,
      fileExists: async (p) => p === bundledPath, // setting is NOT an executable file
      which: async () => pathHit,
      probeVersion: alwaysOk,
    });
    assert.deepEqual(res.hit, { path: bundledPath, source: 'bundled', version: '9.9.9' });
    assert.ok(res.settingError, 'the rejected explicit setting must be surfaced');
    assert.match(res.settingError!, /not an executable file/);
    assert.match(res.settingError!, new RegExp(settingPath.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')));
  });

  test('setting path that exists but fails --version → rejected + error surfaced', async () => {
    const res = await resolveLocalBinary({
      settingPath,
      bundledPath,
      preferPathBinary: false,
      fileExists: async () => true, // both setting and bundled look like files
      which: async () => undefined,
      probeVersion: async (p) =>
        p === settingPath
          ? { ok: false, version: 'unknown', error: 'spawn EACCES' }
          : { ok: true, version: '1.2.3' },
    });
    assert.deepEqual(res.hit, { path: bundledPath, source: 'bundled', version: '1.2.3' });
    assert.ok(res.settingError, 'a setting whose --version fails is surfaced');
    assert.match(res.settingError!, /could not be run/);
    assert.match(res.settingError!, /EACCES/);
  });

  // MED regression (b): a corrupt bundled binary (present but --version fails)
  // must NOT shadow a healthy PATH binary under the bundled-first default.
  test('corrupt bundled binary (probe fails) → healthy PATH binary wins', async () => {
    const res = await resolveLocalBinary({
      bundledPath,
      preferPathBinary: false, // bundled-first default
      fileExists: async () => true, // both look like files
      which: async () => pathHit,
      probeVersion: async (p) =>
        p === bundledPath
          ? { ok: false, version: 'unknown', error: 'exec ENOEXEC' }
          : { ok: true, version: '2.0.0' },
    });
    assert.deepEqual(res.hit, { path: pathHit, source: 'path', version: '2.0.0' });
    assert.equal(res.settingError, undefined);
  });

  // MED regression (c): when every tier is broken, resolution yields no hit so
  // the caller takes the download path — a corrupt binary never wins by default.
  test('all tiers broken (probe fails everywhere) → no hit (→ download)', async () => {
    const res = await resolveLocalBinary({
      settingPath: '',
      bundledPath,
      preferPathBinary: false,
      fileExists: async () => true, // files exist…
      which: async () => pathHit,
      probeVersion: async () => ({ ok: false, version: 'unknown', error: 'exec ENOEXEC' }), // …but none run
    });
    assert.equal(res.hit, undefined, 'no local tier is acceptable');
    assert.equal(res.settingError, undefined);
  });

  test('accepts a runnable-but-unparseable binary with version "unknown"', async () => {
    const res = await resolveLocalBinary({
      bundledPath,
      preferPathBinary: false,
      fileExists: async (p) => p === bundledPath,
      which: async () => undefined,
      probeVersion: async () => ({ ok: true, version: 'unknown' }), // ran, output unparseable
    });
    assert.deepEqual(res.hit, { path: bundledPath, source: 'bundled', version: 'unknown' });
  });

  test('returns no hit (→ download fallback) when nothing is found anywhere', async () => {
    const res = await resolveLocalBinary({
      settingPath: '',
      bundledPath,
      preferPathBinary: false,
      fileExists: async () => false,
      which: async () => undefined,
      probeVersion: alwaysOk,
    });
    assert.equal(res.hit, undefined);
    assert.equal(res.settingError, undefined);
  });
});
