// Package store is the ONE SQL owner for the hosted cloud-intelligence service
// (plan of record §6 CI-P3). Every statement runs with the privileges of a
// non-login application role via a transaction-scoped `SET LOCAL ROLE`, so RLS
// constrains it and a repository method can never read or write another
// account's rows. The role is chosen at construction (New defaults to sbci_app;
// NewForRole binds sbci_api or sbci_worker for the split api/worker deployment,
// E2 / W6rs) and is emitted as a compile-time-constant SQL literal — never
// interpolated. The single cross-tenant DATA primitive is the
// SECURITY DEFINER lease function (LeaseNextJob); the two auth-bootstrap
// lookups (token introspection, identity-link resolution) are the only other
// cross-tenant reads, each a narrow SECURITY DEFINER function.
//
// UUID handling: primary keys are generated by Postgres (gen_random_uuid()
// DEFAULTs) and read back as text (`id::text`); uuid parameters are passed as
// Go strings and cast in SQL (`$n::uuid`). This keeps the package free of any
// uuid dependency while staying strictly typed at the database.
package store

import (
	"context"
	"errors"
	"fmt"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"

	"github.com/marmutapp/superbased-observer/internal/cloudserver/deletionjournal"
)

// Role is the non-login Postgres role a Store's transactions assume via
// `SET LOCAL ROLE`. Only the three constants below are valid; a Store is never
// constructed with any other value (New defaults to RoleApp, NewForRole
// validates), so the role always maps to a fixed, compile-time-constant SQL
// literal (setLocalRoleSQL) and no caller-supplied string ever reaches SQL.
type Role string

const (
	// RoleApp is the shared application role (operator/admin paths, and the
	// dev/test single-role fallback). It is the default for New.
	RoleApp Role = "sbci_app"
	// RoleAPI is the front-door (serve) least-privilege role (E2 / W6rs).
	RoleAPI Role = "sbci_api"
	// RoleWorker is the inference-worker least-privilege role (E2 / W6rs).
	RoleWorker Role = "sbci_worker"
	// RoleAggregator is the cross-tenant community-aggregation read role (W5).
	// It holds EXECUTE on ONLY the SECURITY DEFINER banding function and no
	// direct table grants, so the sole thing it can do is call
	// sbci_community_bands (floored + k-suppressed cells). The worker assumes it
	// for that one read via WithAggregator; it is deliberately NOT a valid()
	// construction role (a Store is never bound to it), so no ordinary tenant or
	// system path can ever run as the aggregator.
	RoleAggregator Role = "sbci_aggregator"
)

// valid reports whether r is one of the three constructable roles. RoleAggregator
// is intentionally excluded: it is reachable only through WithAggregator, never
// as a Store's standing appRole.
func (r Role) valid() bool {
	switch r {
	case RoleApp, RoleAPI, RoleWorker:
		return true
	default:
		return false
	}
}

// setLocalRoleSQL returns the fixed `SET LOCAL ROLE ...` statement for r as a
// compile-time constant string — the role name is NEVER interpolated, so the
// statement can never be an injection vector. Construction guarantees r is
// valid; the default arm returns the sbci_app literal purely as a fail-safe.
func (r Role) setLocalRoleSQL() string {
	switch r {
	case RoleAPI:
		return `SET LOCAL ROLE sbci_api`
	case RoleWorker:
		return `SET LOCAL ROLE sbci_worker`
	case RoleAggregator:
		return `SET LOCAL ROLE sbci_aggregator`
	case RoleApp:
		return `SET LOCAL ROLE sbci_app`
	default:
		return `SET LOCAL ROLE sbci_app`
	}
}

// Store wraps the pgx pool. It holds no per-request state; tenant scope is
// established per transaction. It also owns the evidence-blob Encryptor seam
// (default AES-256-GCM); SetEvidenceEncryptor swaps it (e.g. a shared
// SBCI_EVIDENCE_KEY across the api + worker processes, or a Key Vault path).
type Store struct {
	pool    *pgxpool.Pool
	enc     Encryptor
	appRole Role
	// deletionJournal is the append-only, restore-domain-external record of
	// account deletions (W6d). It is a HARD dependency of the deletion path:
	// CreateDeletionRequest* refuse to run with it unset, so a deletion can
	// never reach 'done' without a durable record that survives a PITR restore.
	deletionJournal deletionjournal.Journal
	// paddlePrices maps a Paddle price id to the W4 plan it grants (W9). Empty
	// until SetPaddlePriceMap wires the deploy config, so every activation
	// fail-closes as unknown-price until real pri_* ids are provisioned.
	paddlePrices map[string]PaddlePlan
}

// New returns a Store over pool bound to the default sbci_app role, with the
// default (process-random) evidence encryptor.
func New(pool *pgxpool.Pool) *Store {
	return &Store{pool: pool, enc: newDefaultEncryptor(), appRole: RoleApp}
}

// NewForRole returns a Store whose transactions assume role (E2 / W6rs). role
// MUST be one of RoleApp, RoleAPI, RoleWorker; any other value is rejected so a
// mis-wired process fails loudly at construction rather than emitting an
// unexpected SET ROLE.
func NewForRole(pool *pgxpool.Pool, role Role) (*Store, error) {
	if !role.valid() {
		return nil, fmt.Errorf("cloudserver/store.NewForRole: invalid role %q (want sbci_app, sbci_api, or sbci_worker)", role)
	}
	s := New(pool)
	s.appRole = role
	return s, nil
}

// Role returns the application role this Store's transactions assume.
func (s *Store) Role() Role { return s.appRole }

// SetEvidenceEncryptor replaces the evidence-blob encryptor. Call it before any
// blob Put/Get (e.g. at service bootstrap from SBCI_EVIDENCE_KEY).
func (s *Store) SetEvidenceEncryptor(enc Encryptor) {
	if enc != nil {
		s.enc = enc
	}
}

// SetDeletionJournal wires the account-deletion journal (W6d). It must be called
// at service bootstrap (and in tests) before any deletion; the deletion path
// fails closed when it is unset.
func (s *Store) SetDeletionJournal(j deletionjournal.Journal) {
	s.deletionJournal = j
}

// Pool exposes the underlying pool for lifecycle management (Close, Ping).
func (s *Store) Pool() *pgxpool.Pool { return s.pool }

// ErrNotFound is returned by lookups that resolve nothing.
var ErrNotFound = errors.New("cloudserver/store: not found")

// WithAccount runs fn inside a transaction scoped to account: it drops to the
// store's application role and sets the sbci.account_id GUC (both SET LOCAL, so both reset
// when the transaction ends, whether it commits, rolls back, or the connection
// is returned to the pool). fn's error rolls the transaction back.
//
// accountID must be a well-formed UUID string; it is cast to uuid by the GUC's
// consumers (the RLS policies). An empty accountID is rejected so a caller can
// never accidentally open a tenant transaction with a missing-context (which
// would silently match no rows).
func (s *Store) WithAccount(ctx context.Context, accountID string, fn func(ctx context.Context, tx pgx.Tx) error) error {
	if accountID == "" {
		return errors.New("cloudserver/store.WithAccount: empty accountID")
	}
	return s.inTx(ctx, func(ctx context.Context, tx pgx.Tx) error {
		if _, err := tx.Exec(ctx, s.appRole.setLocalRoleSQL()); err != nil {
			return fmt.Errorf("cloudserver/store.WithAccount: set role: %w", err)
		}
		// set_config(..., is_local=true) so the setting is transaction-scoped.
		if _, err := tx.Exec(ctx, `SELECT set_config('sbci.account_id', $1, true)`, accountID); err != nil {
			return fmt.Errorf("cloudserver/store.WithAccount: set tenant: %w", err)
		}
		return fn(ctx, tx)
	})
}

// WithSystem runs fn as the store's application role WITHOUT any tenant context
// — for the system/control-plane tables (accounts, nonces, route registry, kill
// switches, budget, audit) and the SECURITY DEFINER bootstrap functions. It
// deliberately does NOT set sbci.account_id, so any RLS-protected table touched
// here matches no rows (missing-context-deny) — a guard against accidentally
// reaching tenant data on the system path.
func (s *Store) WithSystem(ctx context.Context, fn func(ctx context.Context, tx pgx.Tx) error) error {
	return s.inTx(ctx, func(ctx context.Context, tx pgx.Tx) error {
		if _, err := tx.Exec(ctx, s.appRole.setLocalRoleSQL()); err != nil {
			return fmt.Errorf("cloudserver/store.WithSystem: set role: %w", err)
		}
		// Clear any pre-existing session-level tenant GUC (FB2): a DSN carrying
		// options=-c sbci.account_id=<victim>, or any prior session-level
		// set_config(..., is_local=false) left on a pooled connection, would
		// otherwise make this "system" transaction read that victim's RLS rows
		// instead of the promised missing-context deny. set_config(..., true) is
		// transaction-scoped, so it overrides a lingering session value for the
		// life of this tx and resets when the tx ends.
		if _, err := tx.Exec(ctx, `SELECT set_config('sbci.account_id', '', true)`); err != nil {
			return fmt.Errorf("cloudserver/store.WithSystem: clear tenant: %w", err)
		}
		var noTenant bool
		if err := tx.QueryRow(ctx, `SELECT sbci_current_account() IS NULL`).Scan(&noTenant); err != nil {
			return fmt.Errorf("cloudserver/store.WithSystem: verify no tenant: %w", err)
		}
		if !noTenant {
			return errors.New("cloudserver/store.WithSystem: tenant context still set after clear (fail closed)")
		}
		return fn(ctx, tx)
	})
}

// WithAggregator runs fn as sbci_aggregator with NO tenant context — the single
// cross-tenant community-aggregation read (W5). Unlike WithAccount/WithSystem it
// ignores the store's standing appRole and always emits the fixed
// `SET LOCAL ROLE sbci_aggregator` literal: in production the WORKER store
// (bound to sbci_worker) assumes the aggregator role only for this read, which
// PostgreSQL permits because SET ROLE is authorized against the SESSION login
// role's memberships (granted to the deploy's login principals), not the current
// role. It clears any tenant GUC and asserts none survives, so the aggregation
// can never accidentally run under a tenant scope. The aggregator holds EXECUTE
// on ONLY sbci_community_bands and no table grants, so fn can do nothing but call
// that one floored/suppressed function — a compromised or buggy caller cannot
// read a raw contribution.
func (s *Store) WithAggregator(ctx context.Context, fn func(ctx context.Context, tx pgx.Tx) error) error {
	return s.inTx(ctx, func(ctx context.Context, tx pgx.Tx) error {
		if _, err := tx.Exec(ctx, RoleAggregator.setLocalRoleSQL()); err != nil {
			return fmt.Errorf("cloudserver/store.WithAggregator: set role: %w", err)
		}
		// Transaction-scoped clear of any lingering session-level tenant GUC
		// (same fail-closed guard as WithSystem, FB2).
		if _, err := tx.Exec(ctx, `SELECT set_config('sbci.account_id', '', true)`); err != nil {
			return fmt.Errorf("cloudserver/store.WithAggregator: clear tenant: %w", err)
		}
		var noTenant bool
		if err := tx.QueryRow(ctx, `SELECT sbci_current_account() IS NULL`).Scan(&noTenant); err != nil {
			return fmt.Errorf("cloudserver/store.WithAggregator: verify no tenant: %w", err)
		}
		if !noTenant {
			return errors.New("cloudserver/store.WithAggregator: tenant context still set after clear (fail closed)")
		}
		return fn(ctx, tx)
	})
}

func (s *Store) inTx(ctx context.Context, fn func(ctx context.Context, tx pgx.Tx) error) error {
	tx, err := s.pool.Begin(ctx)
	if err != nil {
		return fmt.Errorf("cloudserver/store: begin: %w", err)
	}
	defer func() { _ = tx.Rollback(ctx) }() // no-op after a successful Commit
	if err := fn(ctx, tx); err != nil {
		return err
	}
	if err := tx.Commit(ctx); err != nil {
		return fmt.Errorf("cloudserver/store: commit: %w", err)
	}
	return nil
}
