-- 077_tooltax_action_type_backfill.sql — GENERATED by internal/db/taxbackfillgen
-- from internal/tooltax. DO NOT EDIT BY HAND.
--
--   regenerate: make taxonomy-migration-build
--   drift gate: make verify-taxonomy-migration
--
-- WHAT THIS REPAIRS. Migration 024 backfilled the Claude Code names that
-- the adapter's private actionMap already knew, and explicitly deferred
-- the rest: "adding categories for these is a separate taxonomy decision".
-- The tool-taxonomy plan (docs/plans/tool-taxonomy-standardization-plan-
-- 2026-07-31.md) is that decision. internal/tooltax now owns one canonical
-- (tool, native tool name) -> action_type table, WP-T3 pointed the
-- claude-code / codex / cowork adapters at it, and this migration applies
-- the SAME table to the rows already on disk — the agent-orchestration and
-- harness families that had no category when they were ingested (codex
-- wait / wait_agent / spawn_agent / send_message / write_stdin, claude-code
-- Monitor / SendMessage / Skill / ToolSearch / ScheduleWakeup /
-- StructuredOutput), plus every other name tooltax resolves, plus the
-- unresolved `mcp__`-namespace rows, which are an MCP identity and
-- not a guess.
--
-- SCOPE — action_type = 'unknown' ONLY. Every statement carries that
-- guard, so this migration can only ever move rows OUT of the unknown
-- bucket. A row an adapter already classified is never re-classified,
-- which means the deliberate adapter semantics the plan calls out stay
-- exactly as they are: the post_tool_batch shadow rows (an mcp__* name
-- recorded under a batch marker) and cowork's semantic remaps.
--
-- SCOPE — tool. actions.tool is a first-class NOT NULL column, so every
-- tool-specific statement scopes with a plain `tool = '<tool>'` predicate
-- (no join, no correlated subquery needed). Tool scoping is what keeps a
-- name that means different things in different harnesses from being
-- flattened; the tool-less statements at the end carry only the names
-- tooltax declares as unambiguous across every adapter.
--
-- PRECEDENCE. Statement order reproduces tooltax.Resolve's top-down walk,
-- and the 'unknown' guard is what makes order load-bearing: whichever
-- statement fires first wins, and later ones see a row that is no longer
-- unknown. The order is therefore, exactly as in the table:
--   1. tool-specific literal names;
--   2. tool-specific name PREFIXES;
--   3. tool-less (any-tool) literal names;
--   4. the tool-less `mcp__` prefix, last.
--
-- EXACT, CASE-SENSITIVE MATCHING. Literal names use `IN (...)` and
-- prefixes use `substr(raw_tool_name, 1, N) = '<prefix>'`, NOT `LIKE`.
-- SQLite's LIKE is ASCII case-INSENSITIVE by default, which would widen a
-- prefix rule beyond what tooltax's own strings.HasPrefix does (and would
-- additionally need ESCAPE handling, since '_' is a LIKE wildcard and every
-- MCP prefix is full of them). substr equality on a BINARY-collated column
-- replays the Go matcher byte for byte. Note this deliberately does NOT
-- replay tooltax.Resolve's second, NORMALIZED pass (lower-cased, '_'/'-'/'.'
-- stripped): that pass is a runtime affordance for adapters that normalize
-- before switching, and replaying it in SQL would retag rows on a fuzzy
-- match. Historical repair takes the exact-name half only.
--
-- IDEMPOTENT. Re-running is a no-op: the first run cleared 'unknown' for
-- every row these predicates can reach, and nothing here can match a row
-- it already updated.
--
-- NODE-LOCAL. actions.action_type is already on the org push wire; this
-- changes values, not shape, so there is no paired server migration.

UPDATE actions
   SET action_type = 'edit_file'
 WHERE tool = 'aider'
   AND action_type = 'unknown'
   AND raw_tool_name = 'aider.apply_edit';

UPDATE actions
   SET action_type = 'run_command'
 WHERE tool = 'aider'
   AND action_type = 'unknown'
   AND raw_tool_name = 'aider.run_command';

UPDATE actions
   SET action_type = 'edit_file'
 WHERE tool = 'antigravity'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'applypatch', 'edit', 'editfile', 'patch', 'replace',
     'replacefilecontent', 'structured.artifact_write',
     'transcript.code_action'
   );

UPDATE actions
   SET action_type = 'read_file'
 WHERE tool = 'antigravity'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'cat', 'read', 'readfile', 'structured.file_view',
     'transcript.view_file', 'view', 'viewfile'
   );

UPDATE actions
   SET action_type = 'run_command'
 WHERE tool = 'antigravity'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'bash', 'cmd', 'cmdexe', 'exec', 'execute', 'powershell',
     'pwsh', 'run', 'runcommand', 'runshellcommand', 'shell',
     'structured.run_command', 'transcript.run_command'
   );

UPDATE actions
   SET action_type = 'search_files'
 WHERE tool = 'antigravity'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'filesearch', 'findbyname', 'findfiles', 'glob', 'listdir',
     'listfiles', 'ls', 'transcript.list_directory'
   );

UPDATE actions
   SET action_type = 'search_text'
 WHERE tool = 'antigravity'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'findtext', 'grep', 'searchtext', 'transcript.grep_search'
   );

UPDATE actions
   SET action_type = 'web_fetch'
 WHERE tool = 'antigravity'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'fetch', 'fetchurl', 'fetchwebpage', 'webfetch'
   );

UPDATE actions
   SET action_type = 'web_search'
 WHERE tool = 'antigravity'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'googlewebsearch', 'search', 'websearch'
   );

UPDATE actions
   SET action_type = 'write_file'
 WHERE tool = 'antigravity'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'create', 'createfile', 'write', 'writefile', 'writetofile'
   );

UPDATE actions
   SET action_type = 'edit_file'
 WHERE tool = 'antigravity-cli'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'applypatch', 'edit', 'editfile', 'patch', 'replace',
     'replacefilecontent', 'structured.artifact_write',
     'transcript.code_action'
   );

UPDATE actions
   SET action_type = 'read_file'
 WHERE tool = 'antigravity-cli'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'cat', 'read', 'readfile', 'structured.file_view',
     'transcript.view_file', 'view', 'viewfile'
   );

UPDATE actions
   SET action_type = 'run_command'
 WHERE tool = 'antigravity-cli'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'bash', 'cmd', 'cmdexe', 'exec', 'execute', 'powershell',
     'pwsh', 'run', 'runcommand', 'runshellcommand', 'shell',
     'structured.run_command', 'transcript.run_command'
   );

UPDATE actions
   SET action_type = 'search_files'
 WHERE tool = 'antigravity-cli'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'filesearch', 'findbyname', 'findfiles', 'glob', 'listdir',
     'listfiles', 'ls', 'transcript.list_directory'
   );

UPDATE actions
   SET action_type = 'search_text'
 WHERE tool = 'antigravity-cli'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'findtext', 'grep', 'searchtext', 'transcript.grep_search'
   );

UPDATE actions
   SET action_type = 'web_fetch'
 WHERE tool = 'antigravity-cli'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'fetch', 'fetchurl', 'fetchwebpage', 'webfetch'
   );

UPDATE actions
   SET action_type = 'web_search'
 WHERE tool = 'antigravity-cli'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'googlewebsearch', 'search', 'websearch'
   );

UPDATE actions
   SET action_type = 'write_file'
 WHERE tool = 'antigravity-cli'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'create', 'createfile', 'write', 'writefile', 'writetofile'
   );

UPDATE actions
   SET action_type = 'agent_control'
 WHERE tool = 'claude-code'
   AND action_type = 'unknown'
   AND raw_tool_name = 'Monitor';

UPDATE actions
   SET action_type = 'agent_message'
 WHERE tool = 'claude-code'
   AND action_type = 'unknown'
   AND raw_tool_name = 'SendMessage';

UPDATE actions
   SET action_type = 'ask_user'
 WHERE tool = 'claude-code'
   AND action_type = 'unknown'
   AND raw_tool_name = 'AskUserQuestion';

UPDATE actions
   SET action_type = 'edit_file'
 WHERE tool = 'claude-code'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'Edit', 'MultiEdit', 'NotebookEdit'
   );

UPDATE actions
   SET action_type = 'harness_call'
 WHERE tool = 'claude-code'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'Artifact', 'SendUserFile', 'StructuredOutput', 'Workflow'
   );

UPDATE actions
   SET action_type = 'notification'
 WHERE tool = 'claude-code'
   AND action_type = 'unknown'
   AND raw_tool_name = 'PushNotification';

UPDATE actions
   SET action_type = 'permission_mode'
 WHERE tool = 'claude-code'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'EnterPlanMode', 'ExitPlanMode'
   );

UPDATE actions
   SET action_type = 'read_file'
 WHERE tool = 'claude-code'
   AND action_type = 'unknown'
   AND raw_tool_name = 'Read';

UPDATE actions
   SET action_type = 'run_command'
 WHERE tool = 'claude-code'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'Bash', 'PowerShell', 'cmd', 'cmd.exe', 'powershell', 'pwsh',
     'sh'
   );

UPDATE actions
   SET action_type = 'schedule'
 WHERE tool = 'claude-code'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'CronCreate', 'CronDelete', 'CronList', 'ScheduleWakeup'
   );

UPDATE actions
   SET action_type = 'search_files'
 WHERE tool = 'claude-code'
   AND action_type = 'unknown'
   AND raw_tool_name = 'Glob';

UPDATE actions
   SET action_type = 'search_text'
 WHERE tool = 'claude-code'
   AND action_type = 'unknown'
   AND raw_tool_name = 'Grep';

UPDATE actions
   SET action_type = 'skill_invoke'
 WHERE tool = 'claude-code'
   AND action_type = 'unknown'
   AND raw_tool_name = 'Skill';

UPDATE actions
   SET action_type = 'spawn_subagent'
 WHERE tool = 'claude-code'
   AND action_type = 'unknown'
   AND raw_tool_name = 'Agent';

UPDATE actions
   SET action_type = 'todo_update'
 WHERE tool = 'claude-code'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'TaskCreate', 'TaskGet', 'TaskList', 'TaskOutput',
     'TaskStop', 'TaskUpdate', 'TodoWrite'
   );

UPDATE actions
   SET action_type = 'tool_search'
 WHERE tool = 'claude-code'
   AND action_type = 'unknown'
   AND raw_tool_name = 'ToolSearch';

UPDATE actions
   SET action_type = 'web_fetch'
 WHERE tool = 'claude-code'
   AND action_type = 'unknown'
   AND raw_tool_name = 'WebFetch';

UPDATE actions
   SET action_type = 'web_search'
 WHERE tool = 'claude-code'
   AND action_type = 'unknown'
   AND raw_tool_name = 'WebSearch';

UPDATE actions
   SET action_type = 'worktree_create'
 WHERE tool = 'claude-code'
   AND action_type = 'unknown'
   AND raw_tool_name = 'EnterWorktree';

UPDATE actions
   SET action_type = 'worktree_remove'
 WHERE tool = 'claude-code'
   AND action_type = 'unknown'
   AND raw_tool_name = 'ExitWorktree';

UPDATE actions
   SET action_type = 'write_file'
 WHERE tool = 'claude-code'
   AND action_type = 'unknown'
   AND raw_tool_name = 'Write';

UPDATE actions
   SET action_type = 'ask_user'
 WHERE tool = 'cline'
   AND action_type = 'unknown'
   AND raw_tool_name = 'ask_followup_question';

UPDATE actions
   SET action_type = 'browser_action'
 WHERE tool = 'cline'
   AND action_type = 'unknown'
   AND raw_tool_name = 'browser_action';

UPDATE actions
   SET action_type = 'edit_file'
 WHERE tool = 'cline'
   AND action_type = 'unknown'
   AND raw_tool_name = 'replace_in_file';

UPDATE actions
   SET action_type = 'mcp_call'
 WHERE tool = 'cline'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'access_mcp_resource', 'use_mcp_tool'
   );

UPDATE actions
   SET action_type = 'read_file'
 WHERE tool = 'cline'
   AND action_type = 'unknown'
   AND raw_tool_name = 'read_file';

UPDATE actions
   SET action_type = 'run_command'
 WHERE tool = 'cline'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'bash', 'cmd', 'cmd.exe', 'execute_command', 'powershell',
     'pwsh', 'sh'
   );

UPDATE actions
   SET action_type = 'search_files'
 WHERE tool = 'cline'
   AND action_type = 'unknown'
   AND raw_tool_name = 'list_files';

UPDATE actions
   SET action_type = 'search_text'
 WHERE tool = 'cline'
   AND action_type = 'unknown'
   AND raw_tool_name = 'search_files';

UPDATE actions
   SET action_type = 'task_complete'
 WHERE tool = 'cline'
   AND action_type = 'unknown'
   AND raw_tool_name = 'attempt_completion';

UPDATE actions
   SET action_type = 'write_file'
 WHERE tool = 'cline'
   AND action_type = 'unknown'
   AND raw_tool_name = 'write_to_file';

UPDATE actions
   SET action_type = 'ask_user'
 WHERE tool = 'cline-cli'
   AND action_type = 'unknown'
   AND raw_tool_name = 'ask_question';

UPDATE actions
   SET action_type = 'edit_file'
 WHERE tool = 'cline-cli'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'apply_patch', 'editor'
   );

UPDATE actions
   SET action_type = 'mcp_call'
 WHERE tool = 'cline-cli'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'skills', 'team_attach_outcome_fragment', 'team_await_runs',
     'team_broadcast', 'team_cancel_run', 'team_cleanup',
     'team_create_outcome', 'team_finalize_outcome',
     'team_list_outcomes', 'team_list_runs', 'team_mission_log',
     'team_read_mailbox', 'team_review_outcome_fragment',
     'team_run_task', 'team_send_message',
     'team_shutdown_teammate', 'team_status', 'team_task'
   );

UPDATE actions
   SET action_type = 'read_file'
 WHERE tool = 'cline-cli'
   AND action_type = 'unknown'
   AND raw_tool_name = 'read_files';

UPDATE actions
   SET action_type = 'run_command'
 WHERE tool = 'cline-cli'
   AND action_type = 'unknown'
   AND raw_tool_name = 'run_commands';

UPDATE actions
   SET action_type = 'search_files'
 WHERE tool = 'cline-cli'
   AND action_type = 'unknown'
   AND raw_tool_name = 'search_codebase';

UPDATE actions
   SET action_type = 'spawn_subagent'
 WHERE tool = 'cline-cli'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'spawn_agent', 'team_spawn_teammate'
   );

UPDATE actions
   SET action_type = 'task_complete'
 WHERE tool = 'cline-cli'
   AND action_type = 'unknown'
   AND raw_tool_name = 'submit_and_exit';

UPDATE actions
   SET action_type = 'web_fetch'
 WHERE tool = 'cline-cli'
   AND action_type = 'unknown'
   AND raw_tool_name = 'fetch_web_content';

UPDATE actions
   SET action_type = 'mcp_call'
 WHERE tool = 'cline-cli'
   AND action_type = 'unknown'
   AND substr(raw_tool_name, 1, 4) = 'mcp_';

UPDATE actions
   SET action_type = 'agent_control'
 WHERE tool = 'codex'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'interrupt_agent', 'list_agents', 'list_threads',
     'read_thread', 'read_thread_terminal'
   );

UPDATE actions
   SET action_type = 'agent_message'
 WHERE tool = 'codex'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'followup_task', 'send_message'
   );

UPDATE actions
   SET action_type = 'ask_user'
 WHERE tool = 'codex'
   AND action_type = 'unknown'
   AND raw_tool_name = 'request_user_input';

UPDATE actions
   SET action_type = 'edit_file'
 WHERE tool = 'codex'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'apply_patch', 'edit_file', 'patch', 'patch_apply_end',
     'replace'
   );

UPDATE actions
   SET action_type = 'harness_call'
 WHERE tool = 'codex'
   AND action_type = 'unknown'
   AND raw_tool_name = 'imagegen';

UPDATE actions
   SET action_type = 'mcp_call'
 WHERE tool = 'codex'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'check_command_freshness', 'get_action_details',
     'get_cost_summary', 'get_failure_context', 'get_file',
     'get_last_test_result', 'get_project_patterns',
     'get_session_recovery_context', 'get_session_summary', 'js',
     'list_actions_around', 'list_mcp_resource_templates',
     'list_mcp_resources', 'load_workspace_dependencies',
     'mcp_tool_call_end', 'search_past_outputs'
   );

UPDATE actions
   SET action_type = 'read_file'
 WHERE tool = 'codex'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'file_read', 'open_file', 'read_file', 'view_image'
   );

UPDATE actions
   SET action_type = 'run_command'
 WHERE tool = 'codex'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'Bash', 'cmd.exe', 'command', 'exec', 'exec_command',
     'execute', 'powershell', 'pwsh', 'shell', 'shell_command'
   );

UPDATE actions
   SET action_type = 'search_files'
 WHERE tool = 'codex'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'file_search', 'find', 'glob', 'list_directory', 'list_files'
   );

UPDATE actions
   SET action_type = 'search_text'
 WHERE tool = 'codex'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'find_in_files', 'find_text', 'grep', 'search'
   );

UPDATE actions
   SET action_type = 'spawn_subagent'
 WHERE tool = 'codex'
   AND action_type = 'unknown'
   AND raw_tool_name = 'spawn_agent';

UPDATE actions
   SET action_type = 'stdin_write'
 WHERE tool = 'codex'
   AND action_type = 'unknown'
   AND raw_tool_name = 'write_stdin';

UPDATE actions
   SET action_type = 'subagent_wait'
 WHERE tool = 'codex'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'wait', 'wait_agent'
   );

UPDATE actions
   SET action_type = 'todo_update'
 WHERE tool = 'codex'
   AND action_type = 'unknown'
   AND raw_tool_name = 'update_plan';

UPDATE actions
   SET action_type = 'web_fetch'
 WHERE tool = 'codex'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'fetch_url', 'web_fetch'
   );

UPDATE actions
   SET action_type = 'web_search'
 WHERE tool = 'codex'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'web_search', 'web_search_end'
   );

UPDATE actions
   SET action_type = 'write_file'
 WHERE tool = 'codex'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'create_file', 'file_write', 'write_file'
   );

UPDATE actions
   SET action_type = 'ask_user'
 WHERE tool = 'command-code'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'askfollowupquestion', 'askuser', 'askuserquestion'
   );

UPDATE actions
   SET action_type = 'edit_file'
 WHERE tool = 'command-code'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'applypatch', 'edit', 'editfile', 'multiedit', 'patch',
     'replace'
   );

UPDATE actions
   SET action_type = 'read_file'
 WHERE tool = 'command-code'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'read', 'readfile', 'readmanyfiles', 'view', 'viewfile'
   );

UPDATE actions
   SET action_type = 'run_command'
 WHERE tool = 'command-code'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'bash', 'exec', 'execute', 'powershell', 'pwsh',
     'runcommand', 'runshellcommand', 'shell', 'shellcommand',
     'terminal'
   );

UPDATE actions
   SET action_type = 'search_files'
 WHERE tool = 'command-code'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'findfiles', 'glob', 'listdir', 'listdirectory', 'listfiles',
     'ls', 'readdirectory', 'searchfiles'
   );

UPDATE actions
   SET action_type = 'search_text'
 WHERE tool = 'command-code'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'codesearch', 'grep', 'ripgrep', 'searchfilecontent',
     'searchtext'
   );

UPDATE actions
   SET action_type = 'spawn_subagent'
 WHERE tool = 'command-code'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'agent', 'delegate', 'spawnagent', 'subagent', 'task'
   );

UPDATE actions
   SET action_type = 'todo_update'
 WHERE tool = 'command-code'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'todo', 'todowrite', 'updateplan', 'updatetodos'
   );

UPDATE actions
   SET action_type = 'web_fetch'
 WHERE tool = 'command-code'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'fetch', 'fetchurl', 'readurl', 'webfetch'
   );

UPDATE actions
   SET action_type = 'web_search'
 WHERE tool = 'command-code'
   AND action_type = 'unknown'
   AND raw_tool_name = 'websearch';

UPDATE actions
   SET action_type = 'write_file'
 WHERE tool = 'command-code'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'createfile', 'write', 'writefile'
   );

UPDATE actions
   SET action_type = 'edit_file'
 WHERE tool = 'copilot'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'applypatch', 'deletefile', 'editfiles',
     'replacelinesinfile', 'replacestringinfile'
   );

UPDATE actions
   SET action_type = 'read_file'
 WHERE tool = 'copilot'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'openfile', 'readfile', 'readsemantic', 'searchbyname',
     'viewimage'
   );

UPDATE actions
   SET action_type = 'run_command'
 WHERE tool = 'copilot'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'bash', 'cmd', 'cmdexe', 'executecommand', 'powershell',
     'pwsh', 'runinterminal', 'shell'
   );

UPDATE actions
   SET action_type = 'search_files'
 WHERE tool = 'copilot'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'filesearch', 'findfiles', 'listdir'
   );

UPDATE actions
   SET action_type = 'search_text'
 WHERE tool = 'copilot'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'findtextinfiles', 'grep', 'grepsearch'
   );

UPDATE actions
   SET action_type = 'spawn_subagent'
 WHERE tool = 'copilot'
   AND action_type = 'unknown'
   AND raw_tool_name = 'runsubagent';

UPDATE actions
   SET action_type = 'todo_update'
 WHERE tool = 'copilot'
   AND action_type = 'unknown'
   AND raw_tool_name = 'managetodolist';

UPDATE actions
   SET action_type = 'web_fetch'
 WHERE tool = 'copilot'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'fetchwebpage', 'webfetch'
   );

UPDATE actions
   SET action_type = 'web_search'
 WHERE tool = 'copilot'
   AND action_type = 'unknown'
   AND raw_tool_name = 'websearch';

UPDATE actions
   SET action_type = 'write_file'
 WHERE tool = 'copilot'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'createfile', 'writefile'
   );

UPDATE actions
   SET action_type = 'ask_user'
 WHERE tool = 'copilot-cli'
   AND action_type = 'unknown'
   AND raw_tool_name = 'ask_user';

UPDATE actions
   SET action_type = 'edit_file'
 WHERE tool = 'copilot-cli'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'edit', 'str_replace_editor'
   );

UPDATE actions
   SET action_type = 'harness_call'
 WHERE tool = 'copilot-cli'
   AND action_type = 'unknown'
   AND raw_tool_name = 'fetch_copilot_cli_documentation';

UPDATE actions
   SET action_type = 'read_file'
 WHERE tool = 'copilot-cli'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'read', 'view'
   );

UPDATE actions
   SET action_type = 'run_command'
 WHERE tool = 'copilot-cli'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'bash', 'cmd', 'cmd.exe', 'powershell', 'pwsh', 'sh', 'shell'
   );

UPDATE actions
   SET action_type = 'search_files'
 WHERE tool = 'copilot-cli'
   AND action_type = 'unknown'
   AND raw_tool_name = 'glob';

UPDATE actions
   SET action_type = 'search_text'
 WHERE tool = 'copilot-cli'
   AND action_type = 'unknown'
   AND raw_tool_name = 'grep';

UPDATE actions
   SET action_type = 'spawn_subagent'
 WHERE tool = 'copilot-cli'
   AND action_type = 'unknown'
   AND raw_tool_name = 'task';

UPDATE actions
   SET action_type = 'web_fetch'
 WHERE tool = 'copilot-cli'
   AND action_type = 'unknown'
   AND raw_tool_name = 'web_fetch';

UPDATE actions
   SET action_type = 'web_search'
 WHERE tool = 'copilot-cli'
   AND action_type = 'unknown'
   AND raw_tool_name = 'web_search';

UPDATE actions
   SET action_type = 'write_file'
 WHERE tool = 'copilot-cli'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'create', 'write'
   );

UPDATE actions
   SET action_type = 'mcp_call'
 WHERE tool = 'copilot-cli'
   AND action_type = 'unknown'
   AND substr(raw_tool_name, 1, 18) = 'github-mcp-server-';

UPDATE actions
   SET action_type = 'ask_user'
 WHERE tool = 'cowork'
   AND action_type = 'unknown'
   AND raw_tool_name = 'AskUserQuestion';

UPDATE actions
   SET action_type = 'edit_file'
 WHERE tool = 'cowork'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'Edit', 'NotebookEdit'
   );

UPDATE actions
   SET action_type = 'mcp_call'
 WHERE tool = 'cowork'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'Skill', 'ToolSearch',
     'mcp__cowork__allow_cowork_file_delete',
     'mcp__cowork__present_files',
     'mcp__cowork__request_cowork_directory',
     'mcp__cowork__send_user_message', 'mcp__visualize__read_me',
     'mcp__visualize__show_widget'
   );

UPDATE actions
   SET action_type = 'read_file'
 WHERE tool = 'cowork'
   AND action_type = 'unknown'
   AND raw_tool_name = 'Read';

UPDATE actions
   SET action_type = 'run_command'
 WHERE tool = 'cowork'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'Bash', 'PowerShell', 'cmd', 'cmd.exe',
     'mcp__workspace__bash', 'powershell', 'pwsh', 'sh'
   );

UPDATE actions
   SET action_type = 'search_files'
 WHERE tool = 'cowork'
   AND action_type = 'unknown'
   AND raw_tool_name = 'Glob';

UPDATE actions
   SET action_type = 'search_text'
 WHERE tool = 'cowork'
   AND action_type = 'unknown'
   AND raw_tool_name = 'Grep';

UPDATE actions
   SET action_type = 'spawn_subagent'
 WHERE tool = 'cowork'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'Agent', 'Task'
   );

UPDATE actions
   SET action_type = 'todo_update'
 WHERE tool = 'cowork'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'TaskCreate', 'TaskGet', 'TaskList', 'TaskOutput',
     'TaskStop', 'TaskUpdate', 'TodoWrite'
   );

UPDATE actions
   SET action_type = 'web_fetch'
 WHERE tool = 'cowork'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'WebFetch', 'mcp__workspace__web_fetch'
   );

UPDATE actions
   SET action_type = 'web_search'
 WHERE tool = 'cowork'
   AND action_type = 'unknown'
   AND raw_tool_name = 'WebSearch';

UPDATE actions
   SET action_type = 'write_file'
 WHERE tool = 'cowork'
   AND action_type = 'unknown'
   AND raw_tool_name = 'Write';

UPDATE actions
   SET action_type = 'edit_file'
 WHERE tool = 'crush'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'edit', 'multiedit', 'patch', 'replace'
   );

UPDATE actions
   SET action_type = 'read_file'
 WHERE tool = 'crush'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'cat', 'read', 'view'
   );

UPDATE actions
   SET action_type = 'run_command'
 WHERE tool = 'crush'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'bash', 'cmd', 'powershell', 'pwsh', 'shell'
   );

UPDATE actions
   SET action_type = 'search_files'
 WHERE tool = 'crush'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'find', 'glob', 'ls'
   );

UPDATE actions
   SET action_type = 'search_text'
 WHERE tool = 'crush'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'grep', 'rg', 'search'
   );

UPDATE actions
   SET action_type = 'spawn_subagent'
 WHERE tool = 'crush'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'agent', 'subagent', 'task'
   );

UPDATE actions
   SET action_type = 'web_fetch'
 WHERE tool = 'crush'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'download', 'fetch', 'http'
   );

UPDATE actions
   SET action_type = 'web_search'
 WHERE tool = 'crush'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'sourcegraph', 'websearch'
   );

UPDATE actions
   SET action_type = 'write_file'
 WHERE tool = 'crush'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'create', 'write'
   );

UPDATE actions
   SET action_type = 'edit_file'
 WHERE tool = 'cursor'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'Delete', 'afterFileEdit', 'applypatch', 'edit', 'editfile',
     'strreplace'
   );

UPDATE actions
   SET action_type = 'mcp_call'
 WHERE tool = 'cursor'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'call_mcp_tool', 'mcp', 'mcptool'
   );

UPDATE actions
   SET action_type = 'read_file'
 WHERE tool = 'cursor'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'beforeReadFile', 'cat', 'read', 'readfile', 'readlints'
   );

UPDATE actions
   SET action_type = 'run_command'
 WHERE tool = 'cursor'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'bash', 'beforeShellExecution', 'cmd', 'cmdexe', 'command',
     'powershell', 'pwsh', 'shell'
   );

UPDATE actions
   SET action_type = 'search_files'
 WHERE tool = 'cursor'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'findfiles', 'glob'
   );

UPDATE actions
   SET action_type = 'search_text'
 WHERE tool = 'cursor'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'grep', 'search', 'searchfiles', 'semanticsearch'
   );

UPDATE actions
   SET action_type = 'spawn_subagent'
 WHERE tool = 'cursor'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'agent', 'subagent'
   );

UPDATE actions
   SET action_type = 'todo_update'
 WHERE tool = 'cursor'
   AND action_type = 'unknown'
   AND raw_tool_name = 'TodoWrite';

UPDATE actions
   SET action_type = 'write_file'
 WHERE tool = 'cursor'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'Write', 'createfile', 'writefile'
   );

UPDATE actions
   SET action_type = 'agent_control'
 WHERE tool = 'deepseek'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'interrupt_agent', 'job_kill', 'job_list', 'job_output',
     'list_agents'
   );

UPDATE actions
   SET action_type = 'agent_message'
 WHERE tool = 'deepseek'
   AND action_type = 'unknown'
   AND raw_tool_name = 'send_message';

UPDATE actions
   SET action_type = 'ask_user'
 WHERE tool = 'deepseek'
   AND action_type = 'unknown'
   AND raw_tool_name = 'ask_user_question';

UPDATE actions
   SET action_type = 'edit_file'
 WHERE tool = 'deepseek'
   AND action_type = 'unknown'
   AND raw_tool_name = 'edit';

UPDATE actions
   SET action_type = 'harness_call'
 WHERE tool = 'deepseek'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'create_goal', 'exit_plan_mode', 'get_goal', 'update_goal'
   );

UPDATE actions
   SET action_type = 'read_file'
 WHERE tool = 'deepseek'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'read', 'read_image'
   );

UPDATE actions
   SET action_type = 'run_command'
 WHERE tool = 'deepseek'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'bash', 'pwsh'
   );

UPDATE actions
   SET action_type = 'search_files'
 WHERE tool = 'deepseek'
   AND action_type = 'unknown'
   AND raw_tool_name = 'glob';

UPDATE actions
   SET action_type = 'search_text'
 WHERE tool = 'deepseek'
   AND action_type = 'unknown'
   AND raw_tool_name = 'grep';

UPDATE actions
   SET action_type = 'skill_invoke'
 WHERE tool = 'deepseek'
   AND action_type = 'unknown'
   AND raw_tool_name = 'skill';

UPDATE actions
   SET action_type = 'spawn_subagent'
 WHERE tool = 'deepseek'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'ralph', 'subagent', 'subagent_fork', 'workflow'
   );

UPDATE actions
   SET action_type = 'todo_update'
 WHERE tool = 'deepseek'
   AND action_type = 'unknown'
   AND raw_tool_name = 'todo_write';

UPDATE actions
   SET action_type = 'web_search'
 WHERE tool = 'deepseek'
   AND action_type = 'unknown'
   AND raw_tool_name = 'web_search';

UPDATE actions
   SET action_type = 'write_file'
 WHERE tool = 'deepseek'
   AND action_type = 'unknown'
   AND raw_tool_name = 'write';

UPDATE actions
   SET action_type = 'ask_user'
 WHERE tool = 'devin'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'ask_question', 'ask_user', 'request_input'
   );

UPDATE actions
   SET action_type = 'edit_file'
 WHERE tool = 'devin'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'apply_patch', 'edit', 'edit_file', 'multiedit', 'replace',
     'str_replace', 'str_replace_editor'
   );

UPDATE actions
   SET action_type = 'permission_request'
 WHERE tool = 'devin'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'request_permission', 'request_scope'
   );

UPDATE actions
   SET action_type = 'read_file'
 WHERE tool = 'devin'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'cat', 'open', 'read', 'read_file', 'view'
   );

UPDATE actions
   SET action_type = 'run_command'
 WHERE tool = 'devin'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'bash', 'command', 'exec', 'run_command', 'run_terminal_cmd',
     'shell'
   );

UPDATE actions
   SET action_type = 'search_files'
 WHERE tool = 'devin'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'find', 'glob', 'list_dir', 'list_files', 'ls'
   );

UPDATE actions
   SET action_type = 'search_text'
 WHERE tool = 'devin'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'codebase_search', 'grep', 'rg', 'search'
   );

UPDATE actions
   SET action_type = 'spawn_subagent'
 WHERE tool = 'devin'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'agent', 'run_subagent', 'spawn_subagent', 'subagent', 'task'
   );

UPDATE actions
   SET action_type = 'web_fetch'
 WHERE tool = 'devin'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'download', 'fetch', 'http', 'read_url', 'web_fetch'
   );

UPDATE actions
   SET action_type = 'web_search'
 WHERE tool = 'devin'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'search_web', 'web_search', 'websearch'
   );

UPDATE actions
   SET action_type = 'write_file'
 WHERE tool = 'devin'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'create', 'create_file', 'write', 'write_file'
   );

UPDATE actions
   SET action_type = 'ask_user'
 WHERE tool = 'droid'
   AND action_type = 'unknown'
   AND raw_tool_name = 'AskUser';

UPDATE actions
   SET action_type = 'config_change'
 WHERE tool = 'droid'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'CreateAutomation', 'CronCreate', 'CronDelete', 'CronList',
     'DeleteAutomation', 'EditAutomation', 'ListAutomationRun',
     'ListAutomations', 'ReadAutomation'
   );

UPDATE actions
   SET action_type = 'edit_file'
 WHERE tool = 'droid'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'ApplyPatch', 'Edit', 'MultiEdit'
   );

UPDATE actions
   SET action_type = 'permission_mode'
 WHERE tool = 'droid'
   AND action_type = 'unknown'
   AND raw_tool_name = 'ExitSpecMode';

UPDATE actions
   SET action_type = 'read_file'
 WHERE tool = 'droid'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'Read', 'ReadFile'
   );

UPDATE actions
   SET action_type = 'run_command'
 WHERE tool = 'droid'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'Bash', 'Execute'
   );

UPDATE actions
   SET action_type = 'search_files'
 WHERE tool = 'droid'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'Glob', 'LS'
   );

UPDATE actions
   SET action_type = 'search_text'
 WHERE tool = 'droid'
   AND action_type = 'unknown'
   AND raw_tool_name = 'Grep';

UPDATE actions
   SET action_type = 'spawn_subagent'
 WHERE tool = 'droid'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'Task', 'TaskOutput', 'TaskStop'
   );

UPDATE actions
   SET action_type = 'todo_update'
 WHERE tool = 'droid'
   AND action_type = 'unknown'
   AND raw_tool_name = 'TodoWrite';

UPDATE actions
   SET action_type = 'web_fetch'
 WHERE tool = 'droid'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'FetchUrl', 'WebFetch'
   );

UPDATE actions
   SET action_type = 'web_search'
 WHERE tool = 'droid'
   AND action_type = 'unknown'
   AND raw_tool_name = 'WebSearch';

UPDATE actions
   SET action_type = 'write_file'
 WHERE tool = 'droid'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'Create', 'GenerateDroid', 'Write'
   );

UPDATE actions
   SET action_type = 'ask_user'
 WHERE tool = 'freebuff'
   AND action_type = 'unknown'
   AND raw_tool_name = 'ask_user';

UPDATE actions
   SET action_type = 'browser_action'
 WHERE tool = 'freebuff'
   AND action_type = 'unknown'
   AND raw_tool_name = 'browser_use';

UPDATE actions
   SET action_type = 'edit_file'
 WHERE tool = 'freebuff'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'edit_file', 'str_replace'
   );

UPDATE actions
   SET action_type = 'read_file'
 WHERE tool = 'freebuff'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'read_file', 'read_files'
   );

UPDATE actions
   SET action_type = 'run_command'
 WHERE tool = 'freebuff'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'bash', 'run_command', 'run_terminal_command'
   );

UPDATE actions
   SET action_type = 'search_files'
 WHERE tool = 'freebuff'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'find_files', 'glob', 'list_directory'
   );

UPDATE actions
   SET action_type = 'search_text'
 WHERE tool = 'freebuff'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'code_search', 'grep'
   );

UPDATE actions
   SET action_type = 'skill_invoke'
 WHERE tool = 'freebuff'
   AND action_type = 'unknown'
   AND raw_tool_name = 'skill';

UPDATE actions
   SET action_type = 'spawn_subagent'
 WHERE tool = 'freebuff'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'spawn_agent', 'spawn_agents'
   );

UPDATE actions
   SET action_type = 'task_complete'
 WHERE tool = 'freebuff'
   AND action_type = 'unknown'
   AND raw_tool_name = 'set_output';

UPDATE actions
   SET action_type = 'todo_update'
 WHERE tool = 'freebuff'
   AND action_type = 'unknown'
   AND raw_tool_name = 'write_todos';

UPDATE actions
   SET action_type = 'web_fetch'
 WHERE tool = 'freebuff'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'read_url', 'web_fetch'
   );

UPDATE actions
   SET action_type = 'web_search'
 WHERE tool = 'freebuff'
   AND action_type = 'unknown'
   AND raw_tool_name = 'web_search';

UPDATE actions
   SET action_type = 'write_file'
 WHERE tool = 'freebuff'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'create_file', 'write_file'
   );

UPDATE actions
   SET action_type = 'edit_file'
 WHERE tool = 'gemini-cli'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'applypatch', 'edit', 'editfile', 'patch', 'replace'
   );

UPDATE actions
   SET action_type = 'mcp_call'
 WHERE tool = 'gemini-cli'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'memorize', 'savememory'
   );

UPDATE actions
   SET action_type = 'read_file'
 WHERE tool = 'gemini-cli'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'read', 'readfile', 'view', 'viewfile'
   );

UPDATE actions
   SET action_type = 'run_command'
 WHERE tool = 'gemini-cli'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'bash', 'cmd', 'cmdexe', 'exec', 'execute', 'powershell',
     'pwsh', 'runcommand', 'runshellcommand', 'shell'
   );

UPDATE actions
   SET action_type = 'search_files'
 WHERE tool = 'gemini-cli'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'filesearch', 'findfiles', 'glob', 'listdirectory',
     'listfiles', 'ls'
   );

UPDATE actions
   SET action_type = 'search_text'
 WHERE tool = 'gemini-cli'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'findtext', 'grep', 'grepsearch', 'searchtext'
   );

UPDATE actions
   SET action_type = 'spawn_subagent'
 WHERE tool = 'gemini-cli'
   AND action_type = 'unknown'
   AND raw_tool_name = 'invokeagent';

UPDATE actions
   SET action_type = 'task_complete'
 WHERE tool = 'gemini-cli'
   AND action_type = 'unknown'
   AND raw_tool_name = 'complete_task';

UPDATE actions
   SET action_type = 'todo_update'
 WHERE tool = 'gemini-cli'
   AND action_type = 'unknown'
   AND raw_tool_name = 'write_todos';

UPDATE actions
   SET action_type = 'web_fetch'
 WHERE tool = 'gemini-cli'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'fetch', 'fetchurl', 'fetchwebpage', 'webfetch'
   );

UPDATE actions
   SET action_type = 'web_search'
 WHERE tool = 'gemini-cli'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'googlewebsearch', 'search', 'websearch'
   );

UPDATE actions
   SET action_type = 'write_file'
 WHERE tool = 'gemini-cli'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'create', 'createfile', 'write', 'writefile'
   );

UPDATE actions
   SET action_type = 'edit_file'
 WHERE tool = 'goose'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'apply_patch', 'edit', 'edit_file', 'replace', 'str_replace',
     'text_editor'
   );

UPDATE actions
   SET action_type = 'read_file'
 WHERE tool = 'goose'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'cat', 'read', 'read_file', 'view'
   );

UPDATE actions
   SET action_type = 'run_command'
 WHERE tool = 'goose'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'bash', 'command', 'run_command', 'shell', 'terminal'
   );

UPDATE actions
   SET action_type = 'search_files'
 WHERE tool = 'goose'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'find', 'glob', 'list', 'list_dir', 'ls'
   );

UPDATE actions
   SET action_type = 'search_text'
 WHERE tool = 'goose'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'grep', 'rg', 'ripgrep', 'search'
   );

UPDATE actions
   SET action_type = 'web_fetch'
 WHERE tool = 'goose'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'download', 'fetch', 'read_url', 'web_fetch'
   );

UPDATE actions
   SET action_type = 'web_search'
 WHERE tool = 'goose'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'search_web', 'web_search', 'websearch'
   );

UPDATE actions
   SET action_type = 'write_file'
 WHERE tool = 'goose'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'create', 'create_file', 'write', 'write_file'
   );

UPDATE actions
   SET action_type = 'edit_file'
 WHERE tool = 'grok'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'applypatch', 'deletefile', 'edit', 'editfile', 'multiedit',
     'patch', 'removefile', 'replace', 'searchreplace',
     'strreplace'
   );

UPDATE actions
   SET action_type = 'read_file'
 WHERE tool = 'grok'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'cat', 'read', 'readfile', 'view', 'viewfile'
   );

UPDATE actions
   SET action_type = 'run_command'
 WHERE tool = 'grok'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'bash', 'cmd', 'exec', 'execute', 'powershell', 'pwsh',
     'runcommand', 'runterminalcommand', 'shell', 'terminal'
   );

UPDATE actions
   SET action_type = 'search_files'
 WHERE tool = 'grok'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'filesearch', 'findfiles', 'glob', 'listdir',
     'listdirectory', 'ls', 'readfolder'
   );

UPDATE actions
   SET action_type = 'search_text'
 WHERE tool = 'grok'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'codesearch', 'findtext', 'grep', 'ripgrep', 'search',
     'searchtext'
   );

UPDATE actions
   SET action_type = 'spawn_subagent'
 WHERE tool = 'grok'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'agent', 'delegate', 'dispatchagent', 'spawnagent',
     'subagent', 'task'
   );

UPDATE actions
   SET action_type = 'todo_update'
 WHERE tool = 'grok'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'planupdate', 'todo', 'todoupdate', 'todowrite', 'updateplan'
   );

UPDATE actions
   SET action_type = 'web_fetch'
 WHERE tool = 'grok'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'browse', 'fetch', 'fetchurl', 'openurl', 'readurl',
     'webfetch'
   );

UPDATE actions
   SET action_type = 'web_search'
 WHERE tool = 'grok'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'browsersearch', 'search_web', 'websearch'
   );

UPDATE actions
   SET action_type = 'write_file'
 WHERE tool = 'grok'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'create', 'createfile', 'newfile', 'write', 'writefile'
   );

UPDATE actions
   SET action_type = 'ask_user'
 WHERE tool = 'hermes'
   AND action_type = 'unknown'
   AND raw_tool_name = 'clarify';

UPDATE actions
   SET action_type = 'browser_action'
 WHERE tool = 'hermes'
   AND action_type = 'unknown'
   AND raw_tool_name = 'computer_use';

UPDATE actions
   SET action_type = 'edit_file'
 WHERE tool = 'hermes'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'apply_diff', 'patch'
   );

UPDATE actions
   SET action_type = 'mcp_call'
 WHERE tool = 'hermes'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'cronjob', 'image_generate', 'memory', 'send_message',
     'session_search', 'skill_manage', 'skill_view',
     'skills_list', 'text_to_speech', 'video_analyze',
     'video_generate', 'vision_analyze'
   );

UPDATE actions
   SET action_type = 'read_file'
 WHERE tool = 'hermes'
   AND action_type = 'unknown'
   AND raw_tool_name = 'read_file';

UPDATE actions
   SET action_type = 'run_command'
 WHERE tool = 'hermes'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'execute_code', 'process', 'terminal'
   );

UPDATE actions
   SET action_type = 'search_files'
 WHERE tool = 'hermes'
   AND action_type = 'unknown'
   AND raw_tool_name = 'search_files';

UPDATE actions
   SET action_type = 'spawn_subagent'
 WHERE tool = 'hermes'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'delegate_task', 'mixture_of_agents'
   );

UPDATE actions
   SET action_type = 'todo_update'
 WHERE tool = 'hermes'
   AND action_type = 'unknown'
   AND raw_tool_name = 'todo';

UPDATE actions
   SET action_type = 'web_fetch'
 WHERE tool = 'hermes'
   AND action_type = 'unknown'
   AND raw_tool_name = 'web_extract';

UPDATE actions
   SET action_type = 'web_search'
 WHERE tool = 'hermes'
   AND action_type = 'unknown'
   AND raw_tool_name = 'web_search';

UPDATE actions
   SET action_type = 'write_file'
 WHERE tool = 'hermes'
   AND action_type = 'unknown'
   AND raw_tool_name = 'write_file';

UPDATE actions
   SET action_type = 'browser_action'
 WHERE tool = 'hermes'
   AND action_type = 'unknown'
   AND substr(raw_tool_name, 1, 8) = 'browser_';

UPDATE actions
   SET action_type = 'mcp_call'
 WHERE tool = 'hermes'
   AND action_type = 'unknown'
   AND substr(raw_tool_name, 1, 4) = 'mcp_';

UPDATE actions
   SET action_type = 'edit_file'
 WHERE tool = 'junie'
   AND action_type = 'unknown'
   AND raw_tool_name = 'idea/apply_patch';

UPDATE actions
   SET action_type = 'run_command'
 WHERE tool = 'junie'
   AND action_type = 'unknown'
   AND raw_tool_name = 'idea/execute_terminal_command';

UPDATE actions
   SET action_type = 'search_files'
 WHERE tool = 'junie'
   AND action_type = 'unknown'
   AND raw_tool_name = 'idea/list_directory_tree';

UPDATE actions
   SET action_type = 'write_file'
 WHERE tool = 'junie'
   AND action_type = 'unknown'
   AND raw_tool_name = 'idea/create_new_file';

UPDATE actions
   SET action_type = 'ask_user'
 WHERE tool = 'kilo-code'
   AND action_type = 'unknown'
   AND raw_tool_name = 'ask_followup_question';

UPDATE actions
   SET action_type = 'browser_action'
 WHERE tool = 'kilo-code'
   AND action_type = 'unknown'
   AND raw_tool_name = 'browser_action';

UPDATE actions
   SET action_type = 'edit_file'
 WHERE tool = 'kilo-code'
   AND action_type = 'unknown'
   AND raw_tool_name = 'replace_in_file';

UPDATE actions
   SET action_type = 'mcp_call'
 WHERE tool = 'kilo-code'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'access_mcp_resource', 'use_mcp_tool'
   );

UPDATE actions
   SET action_type = 'read_file'
 WHERE tool = 'kilo-code'
   AND action_type = 'unknown'
   AND raw_tool_name = 'read_file';

UPDATE actions
   SET action_type = 'run_command'
 WHERE tool = 'kilo-code'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'bash', 'cmd', 'cmd.exe', 'execute_command', 'powershell',
     'pwsh', 'sh'
   );

UPDATE actions
   SET action_type = 'search_files'
 WHERE tool = 'kilo-code'
   AND action_type = 'unknown'
   AND raw_tool_name = 'list_files';

UPDATE actions
   SET action_type = 'search_text'
 WHERE tool = 'kilo-code'
   AND action_type = 'unknown'
   AND raw_tool_name = 'search_files';

UPDATE actions
   SET action_type = 'task_complete'
 WHERE tool = 'kilo-code'
   AND action_type = 'unknown'
   AND raw_tool_name = 'attempt_completion';

UPDATE actions
   SET action_type = 'write_file'
 WHERE tool = 'kilo-code'
   AND action_type = 'unknown'
   AND raw_tool_name = 'write_to_file';

UPDATE actions
   SET action_type = 'edit_file'
 WHERE tool = 'kilo-code-cli'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'apply_patch', 'applypatch', 'edit', 'multiedit', 'patch',
     'replace'
   );

UPDATE actions
   SET action_type = 'harness_call'
 WHERE tool = 'kilo-code-cli'
   AND action_type = 'unknown'
   AND raw_tool_name = 'kilo-code-cli.step_finish';

UPDATE actions
   SET action_type = 'read_file'
 WHERE tool = 'kilo-code-cli'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'cat', 'read', 'view'
   );

UPDATE actions
   SET action_type = 'run_command'
 WHERE tool = 'kilo-code-cli'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'bash', 'cmd', 'cmd.exe', 'command', 'powershell', 'pwsh',
     'shell'
   );

UPDATE actions
   SET action_type = 'search_files'
 WHERE tool = 'kilo-code-cli'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'find', 'glob', 'list', 'ls'
   );

UPDATE actions
   SET action_type = 'search_text'
 WHERE tool = 'kilo-code-cli'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'grep', 'rg', 'search'
   );

UPDATE actions
   SET action_type = 'spawn_subagent'
 WHERE tool = 'kilo-code-cli'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'agent', 'subagent', 'task'
   );

UPDATE actions
   SET action_type = 'todo_update'
 WHERE tool = 'kilo-code-cli'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'todo', 'todoread', 'todowrite'
   );

UPDATE actions
   SET action_type = 'web_fetch'
 WHERE tool = 'kilo-code-cli'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'fetch', 'http', 'webfetch'
   );

UPDATE actions
   SET action_type = 'web_search'
 WHERE tool = 'kilo-code-cli'
   AND action_type = 'unknown'
   AND raw_tool_name = 'websearch';

UPDATE actions
   SET action_type = 'write_file'
 WHERE tool = 'kilo-code-cli'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'create', 'write'
   );

UPDATE actions
   SET action_type = 'edit_file'
 WHERE tool = 'kimi-code'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'applypatch', 'edit', 'editfile', 'patch', 'replace'
   );

UPDATE actions
   SET action_type = 'read_file'
 WHERE tool = 'kimi-code'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'read', 'readfile', 'readmediafile', 'view'
   );

UPDATE actions
   SET action_type = 'run_command'
 WHERE tool = 'kimi-code'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'bash', 'exec', 'run', 'runcommand', 'shell', 'terminal'
   );

UPDATE actions
   SET action_type = 'search_files'
 WHERE tool = 'kimi-code'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'findfiles', 'glob', 'listdirectory', 'listfiles', 'ls'
   );

UPDATE actions
   SET action_type = 'search_text'
 WHERE tool = 'kimi-code'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'findtext', 'grep', 'ripgrep', 'searchtext'
   );

UPDATE actions
   SET action_type = 'spawn_subagent'
 WHERE tool = 'kimi-code'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'agent', 'agentswarm', 'delegate', 'spawnagent', 'subagent'
   );

UPDATE actions
   SET action_type = 'todo_update'
 WHERE tool = 'kimi-code'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'todo', 'todolist', 'todowrite'
   );

UPDATE actions
   SET action_type = 'web_fetch'
 WHERE tool = 'kimi-code'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'fetch', 'fetchurl', 'fetchwebpage', 'webfetch'
   );

UPDATE actions
   SET action_type = 'web_search'
 WHERE tool = 'kimi-code'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'search', 'websearch'
   );

UPDATE actions
   SET action_type = 'write_file'
 WHERE tool = 'kimi-code'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'createfile', 'write', 'writefile'
   );

UPDATE actions
   SET action_type = 'edit_file'
 WHERE tool = 'kiro-cli'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'delete_file', 'str_replace'
   );

UPDATE actions
   SET action_type = 'read_file'
 WHERE tool = 'kiro-cli'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'fs_read', 'read', 'read_file'
   );

UPDATE actions
   SET action_type = 'run_command'
 WHERE tool = 'kiro-cli'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'execute_bash', 'execute_cmd', 'execute_pwsh', 'shell'
   );

UPDATE actions
   SET action_type = 'search_files'
 WHERE tool = 'kiro-cli'
   AND action_type = 'unknown'
   AND raw_tool_name = 'list_directory';

UPDATE actions
   SET action_type = 'todo_update'
 WHERE tool = 'kiro-cli'
   AND action_type = 'unknown'
   AND raw_tool_name = 'todo_list';

UPDATE actions
   SET action_type = 'write_file'
 WHERE tool = 'kiro-cli'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'fs_write', 'write'
   );

UPDATE actions
   SET action_type = 'edit_file'
 WHERE tool = 'kiro-crew'
   AND action_type = 'unknown'
   AND raw_tool_name = 'edit';

UPDATE actions
   SET action_type = 'read_file'
 WHERE tool = 'kiro-crew'
   AND action_type = 'unknown'
   AND raw_tool_name = 'read';

UPDATE actions
   SET action_type = 'run_command'
 WHERE tool = 'kiro-crew'
   AND action_type = 'unknown'
   AND raw_tool_name = 'execute';

UPDATE actions
   SET action_type = 'ask_user'
 WHERE tool = 'mistral-code'
   AND action_type = 'unknown'
   AND raw_tool_name = 'ask_user_question';

UPDATE actions
   SET action_type = 'edit_file'
 WHERE tool = 'mistral-code'
   AND action_type = 'unknown'
   AND raw_tool_name = 'edit';

UPDATE actions
   SET action_type = 'read_file'
 WHERE tool = 'mistral-code'
   AND action_type = 'unknown'
   AND raw_tool_name = 'read_file';

UPDATE actions
   SET action_type = 'run_command'
 WHERE tool = 'mistral-code'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'bash', 'bash_log_file', 'bash_output', 'bash_sessions',
     'bash_stdin'
   );

UPDATE actions
   SET action_type = 'search_text'
 WHERE tool = 'mistral-code'
   AND action_type = 'unknown'
   AND raw_tool_name = 'grep';

UPDATE actions
   SET action_type = 'skill_invoke'
 WHERE tool = 'mistral-code'
   AND action_type = 'unknown'
   AND raw_tool_name = 'skill';

UPDATE actions
   SET action_type = 'spawn_subagent'
 WHERE tool = 'mistral-code'
   AND action_type = 'unknown'
   AND raw_tool_name = 'task';

UPDATE actions
   SET action_type = 'todo_update'
 WHERE tool = 'mistral-code'
   AND action_type = 'unknown'
   AND raw_tool_name = 'todo';

UPDATE actions
   SET action_type = 'web_fetch'
 WHERE tool = 'mistral-code'
   AND action_type = 'unknown'
   AND raw_tool_name = 'web_fetch';

UPDATE actions
   SET action_type = 'web_search'
 WHERE tool = 'mistral-code'
   AND action_type = 'unknown'
   AND raw_tool_name = 'web_search';

UPDATE actions
   SET action_type = 'write_file'
 WHERE tool = 'mistral-code'
   AND action_type = 'unknown'
   AND raw_tool_name = 'write_file';

UPDATE actions
   SET action_type = 'ask_user'
 WHERE tool = 'muse'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'askuser', 'askuserquestion'
   );

UPDATE actions
   SET action_type = 'edit_file'
 WHERE tool = 'muse'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'applypatch', 'edit', 'editfile', 'multiedit', 'patch',
     'replace'
   );

UPDATE actions
   SET action_type = 'harness_call'
 WHERE tool = 'muse'
   AND action_type = 'unknown'
   AND raw_tool_name = 'submitreminderdecision';

UPDATE actions
   SET action_type = 'read_file'
 WHERE tool = 'muse'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'read', 'readfile', 'readmanyfiles', 'view', 'viewfile'
   );

UPDATE actions
   SET action_type = 'run_command'
 WHERE tool = 'muse'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'bash', 'exec', 'execcommand', 'execute', 'runcommand',
     'shell', 'terminal'
   );

UPDATE actions
   SET action_type = 'search_files'
 WHERE tool = 'muse'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'findfiles', 'glob', 'listdir', 'listdirectory', 'listfiles',
     'searchfiles'
   );

UPDATE actions
   SET action_type = 'search_text'
 WHERE tool = 'muse'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'codesearch', 'grep', 'ripgrep', 'search', 'searchtext'
   );

UPDATE actions
   SET action_type = 'skill_invoke'
 WHERE tool = 'muse'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'readskill', 'skill', 'useskill'
   );

UPDATE actions
   SET action_type = 'spawn_subagent'
 WHERE tool = 'muse'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'agent', 'delegate', 'spawnagent', 'subagent', 'task'
   );

UPDATE actions
   SET action_type = 'todo_update'
 WHERE tool = 'muse'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'todo', 'todowrite', 'updateplan', 'updatetodos'
   );

UPDATE actions
   SET action_type = 'web_fetch'
 WHERE tool = 'muse'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'fetch', 'fetchurl', 'readurl', 'webfetch'
   );

UPDATE actions
   SET action_type = 'web_search'
 WHERE tool = 'muse'
   AND action_type = 'unknown'
   AND raw_tool_name = 'websearch';

UPDATE actions
   SET action_type = 'write_file'
 WHERE tool = 'muse'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'createfile', 'write', 'writefile'
   );

UPDATE actions
   SET action_type = 'agent_control'
 WHERE tool = 'open-interpreter'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'interrupt_agent', 'list_agents', 'list_threads',
     'read_thread', 'read_thread_terminal'
   );

UPDATE actions
   SET action_type = 'agent_message'
 WHERE tool = 'open-interpreter'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'followup_task', 'send_message'
   );

UPDATE actions
   SET action_type = 'ask_user'
 WHERE tool = 'open-interpreter'
   AND action_type = 'unknown'
   AND raw_tool_name = 'request_user_input';

UPDATE actions
   SET action_type = 'edit_file'
 WHERE tool = 'open-interpreter'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'apply_patch', 'edit_file', 'patch', 'patch_apply_end',
     'replace'
   );

UPDATE actions
   SET action_type = 'harness_call'
 WHERE tool = 'open-interpreter'
   AND action_type = 'unknown'
   AND raw_tool_name = 'imagegen';

UPDATE actions
   SET action_type = 'mcp_call'
 WHERE tool = 'open-interpreter'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'check_command_freshness', 'get_action_details',
     'get_cost_summary', 'get_failure_context', 'get_file',
     'get_last_test_result', 'get_project_patterns',
     'get_session_recovery_context', 'get_session_summary', 'js',
     'list_actions_around', 'list_mcp_resource_templates',
     'list_mcp_resources', 'load_workspace_dependencies',
     'mcp_tool_call_end', 'search_past_outputs'
   );

UPDATE actions
   SET action_type = 'read_file'
 WHERE tool = 'open-interpreter'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'file_read', 'open_file', 'read_file', 'view_image'
   );

UPDATE actions
   SET action_type = 'run_command'
 WHERE tool = 'open-interpreter'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'Bash', 'cmd.exe', 'command', 'exec', 'exec_command',
     'execute', 'powershell', 'pwsh', 'shell', 'shell_command'
   );

UPDATE actions
   SET action_type = 'search_files'
 WHERE tool = 'open-interpreter'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'file_search', 'find', 'glob', 'list_directory', 'list_files'
   );

UPDATE actions
   SET action_type = 'search_text'
 WHERE tool = 'open-interpreter'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'find_in_files', 'find_text', 'grep', 'search'
   );

UPDATE actions
   SET action_type = 'spawn_subagent'
 WHERE tool = 'open-interpreter'
   AND action_type = 'unknown'
   AND raw_tool_name = 'spawn_agent';

UPDATE actions
   SET action_type = 'stdin_write'
 WHERE tool = 'open-interpreter'
   AND action_type = 'unknown'
   AND raw_tool_name = 'write_stdin';

UPDATE actions
   SET action_type = 'subagent_wait'
 WHERE tool = 'open-interpreter'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'wait', 'wait_agent'
   );

UPDATE actions
   SET action_type = 'todo_update'
 WHERE tool = 'open-interpreter'
   AND action_type = 'unknown'
   AND raw_tool_name = 'update_plan';

UPDATE actions
   SET action_type = 'web_fetch'
 WHERE tool = 'open-interpreter'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'fetch_url', 'web_fetch'
   );

UPDATE actions
   SET action_type = 'web_search'
 WHERE tool = 'open-interpreter'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'web_search', 'web_search_end'
   );

UPDATE actions
   SET action_type = 'write_file'
 WHERE tool = 'open-interpreter'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'create_file', 'file_write', 'write_file'
   );

UPDATE actions
   SET action_type = 'browser_action'
 WHERE tool = 'openclaw'
   AND action_type = 'unknown'
   AND raw_tool_name = 'browser';

UPDATE actions
   SET action_type = 'edit_file'
 WHERE tool = 'openclaw'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'edit', 'patch', 'replace'
   );

UPDATE actions
   SET action_type = 'mcp_call'
 WHERE tool = 'openclaw'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'agents_list', 'canvas', 'cron', 'gateway', 'memory_get',
     'message', 'nodes', 'session_status', 'sessions_history',
     'sessions_list', 'sessions_send', 'sessions_yield',
     'subagents', 'tts'
   );

UPDATE actions
   SET action_type = 'read_file'
 WHERE tool = 'openclaw'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'cat', 'read', 'view'
   );

UPDATE actions
   SET action_type = 'run_command'
 WHERE tool = 'openclaw'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'bash', 'cmd', 'cmd.exe', 'command', 'exec', 'powershell',
     'process', 'pwsh', 'shell'
   );

UPDATE actions
   SET action_type = 'search_text'
 WHERE tool = 'openclaw'
   AND action_type = 'unknown'
   AND raw_tool_name = 'memory_search';

UPDATE actions
   SET action_type = 'spawn_subagent'
 WHERE tool = 'openclaw'
   AND action_type = 'unknown'
   AND raw_tool_name = 'sessions_spawn';

UPDATE actions
   SET action_type = 'web_fetch'
 WHERE tool = 'openclaw'
   AND action_type = 'unknown'
   AND raw_tool_name = 'web_fetch';

UPDATE actions
   SET action_type = 'write_file'
 WHERE tool = 'openclaw'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'create', 'write'
   );

UPDATE actions
   SET action_type = 'edit_file'
 WHERE tool = 'opencode'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'apply_patch', 'applypatch', 'edit', 'multiedit', 'patch',
     'replace'
   );

UPDATE actions
   SET action_type = 'harness_call'
 WHERE tool = 'opencode'
   AND action_type = 'unknown'
   AND raw_tool_name = 'opencode.step_finish';

UPDATE actions
   SET action_type = 'read_file'
 WHERE tool = 'opencode'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'cat', 'read', 'view'
   );

UPDATE actions
   SET action_type = 'run_command'
 WHERE tool = 'opencode'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'bash', 'cmd', 'cmd.exe', 'command', 'powershell', 'pwsh',
     'shell'
   );

UPDATE actions
   SET action_type = 'search_files'
 WHERE tool = 'opencode'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'find', 'glob', 'ls'
   );

UPDATE actions
   SET action_type = 'search_text'
 WHERE tool = 'opencode'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'grep', 'rg', 'search'
   );

UPDATE actions
   SET action_type = 'spawn_subagent'
 WHERE tool = 'opencode'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'agent', 'subagent', 'task'
   );

UPDATE actions
   SET action_type = 'todo_update'
 WHERE tool = 'opencode'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'todo', 'todoread', 'todowrite'
   );

UPDATE actions
   SET action_type = 'web_fetch'
 WHERE tool = 'opencode'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'fetch', 'http', 'webfetch'
   );

UPDATE actions
   SET action_type = 'web_search'
 WHERE tool = 'opencode'
   AND action_type = 'unknown'
   AND raw_tool_name = 'websearch';

UPDATE actions
   SET action_type = 'write_file'
 WHERE tool = 'opencode'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'create', 'write'
   );

UPDATE actions
   SET action_type = 'todo_update'
 WHERE tool = 'opencode'
   AND action_type = 'unknown'
   AND substr(raw_tool_name, 1, 5) = 'todo.';

UPDATE actions
   SET action_type = 'edit_file'
 WHERE tool = 'pi'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'apply_patch', 'edit', 'edit_file', 'patch', 'replace'
   );

UPDATE actions
   SET action_type = 'read_file'
 WHERE tool = 'pi'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'cat', 'open_file', 'read', 'read_file', 'view'
   );

UPDATE actions
   SET action_type = 'run_command'
 WHERE tool = 'pi'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'bash', 'cmd', 'cmd.exe', 'command', 'exec', 'execute',
     'powershell', 'pwsh', 'run', 'shell'
   );

UPDATE actions
   SET action_type = 'search_files'
 WHERE tool = 'pi'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'file_search', 'find', 'glob', 'list_files', 'ls'
   );

UPDATE actions
   SET action_type = 'search_text'
 WHERE tool = 'pi'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'find_in_files', 'find_text', 'grep', 'search'
   );

UPDATE actions
   SET action_type = 'web_fetch'
 WHERE tool = 'pi'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'fetch', 'fetch_url', 'web_fetch'
   );

UPDATE actions
   SET action_type = 'web_search'
 WHERE tool = 'pi'
   AND action_type = 'unknown'
   AND raw_tool_name = 'web_search';

UPDATE actions
   SET action_type = 'write_file'
 WHERE tool = 'pi'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'create', 'create_file', 'write', 'write_file'
   );

UPDATE actions
   SET action_type = 'edit_file'
 WHERE tool = 'poolside'
   AND action_type = 'unknown'
   AND raw_tool_name = 'edit';

UPDATE actions
   SET action_type = 'read_file'
 WHERE tool = 'poolside'
   AND action_type = 'unknown'
   AND raw_tool_name = 'read';

UPDATE actions
   SET action_type = 'run_command'
 WHERE tool = 'poolside'
   AND action_type = 'unknown'
   AND raw_tool_name = 'shell';

UPDATE actions
   SET action_type = 'search_files'
 WHERE tool = 'poolside'
   AND action_type = 'unknown'
   AND raw_tool_name = 'list_directory_tree';

UPDATE actions
   SET action_type = 'task_complete'
 WHERE tool = 'poolside'
   AND action_type = 'unknown'
   AND raw_tool_name = 'exit';

UPDATE actions
   SET action_type = 'todo_update'
 WHERE tool = 'poolside'
   AND action_type = 'unknown'
   AND raw_tool_name = 'todo_action';

UPDATE actions
   SET action_type = 'write_file'
 WHERE tool = 'poolside'
   AND action_type = 'unknown'
   AND raw_tool_name = 'write';

UPDATE actions
   SET action_type = 'edit_file'
 WHERE tool = 'prime-agent'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'apply_patch', 'edit', 'edit_file', 'patch'
   );

UPDATE actions
   SET action_type = 'read_file'
 WHERE tool = 'prime-agent'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'cat', 'read', 'read_file', 'view'
   );

UPDATE actions
   SET action_type = 'run_command'
 WHERE tool = 'prime-agent'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'bash', 'command', 'exec', 'execute', 'ipython', 'run',
     'shell'
   );

UPDATE actions
   SET action_type = 'search_files'
 WHERE tool = 'prime-agent'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'find', 'glob', 'list_files', 'ls'
   );

UPDATE actions
   SET action_type = 'search_text'
 WHERE tool = 'prime-agent'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'grep', 'search', 'search_text'
   );

UPDATE actions
   SET action_type = 'web_fetch'
 WHERE tool = 'prime-agent'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'fetch', 'fetch_url', 'web_fetch'
   );

UPDATE actions
   SET action_type = 'web_search'
 WHERE tool = 'prime-agent'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'web_search', 'websearch'
   );

UPDATE actions
   SET action_type = 'write_file'
 WHERE tool = 'prime-agent'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'create', 'create_file', 'write', 'write_file'
   );

UPDATE actions
   SET action_type = 'ask_user'
 WHERE tool = 'qoder'
   AND action_type = 'unknown'
   AND raw_tool_name = 'AskUserQuestion';

UPDATE actions
   SET action_type = 'edit_file'
 WHERE tool = 'qoder'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'Edit', 'MultiEdit', 'NotebookEdit', 'SearchReplace'
   );

UPDATE actions
   SET action_type = 'read_file'
 WHERE tool = 'qoder'
   AND action_type = 'unknown'
   AND raw_tool_name = 'Read';

UPDATE actions
   SET action_type = 'run_command'
 WHERE tool = 'qoder'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'Bash', 'PowerShell', 'cmd', 'cmd.exe', 'powershell', 'pwsh',
     'sh'
   );

UPDATE actions
   SET action_type = 'search_files'
 WHERE tool = 'qoder'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'Glob', 'LS'
   );

UPDATE actions
   SET action_type = 'search_text'
 WHERE tool = 'qoder'
   AND action_type = 'unknown'
   AND raw_tool_name = 'Grep';

UPDATE actions
   SET action_type = 'spawn_subagent'
 WHERE tool = 'qoder'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'Agent', 'Task'
   );

UPDATE actions
   SET action_type = 'todo_update'
 WHERE tool = 'qoder'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'TaskCreate', 'TaskUpdate', 'TodoWrite'
   );

UPDATE actions
   SET action_type = 'web_fetch'
 WHERE tool = 'qoder'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'Fetch', 'WebFetch'
   );

UPDATE actions
   SET action_type = 'web_search'
 WHERE tool = 'qoder'
   AND action_type = 'unknown'
   AND raw_tool_name = 'WebSearch';

UPDATE actions
   SET action_type = 'write_file'
 WHERE tool = 'qoder'
   AND action_type = 'unknown'
   AND raw_tool_name = 'Write';

UPDATE actions
   SET action_type = 'edit_file'
 WHERE tool = 'qwen-code'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'applypatch', 'edit', 'editfile', 'patch', 'replace',
     'smartedit'
   );

UPDATE actions
   SET action_type = 'mcp_call'
 WHERE tool = 'qwen-code'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'memorize', 'savememory'
   );

UPDATE actions
   SET action_type = 'read_file'
 WHERE tool = 'qwen-code'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'read', 'readfile', 'readmanyfiles', 'view', 'viewfile'
   );

UPDATE actions
   SET action_type = 'run_command'
 WHERE tool = 'qwen-code'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'bash', 'cmd', 'cmdexe', 'exec', 'execute', 'powershell',
     'pwsh', 'runcommand', 'runshellcommand', 'shell'
   );

UPDATE actions
   SET action_type = 'search_files'
 WHERE tool = 'qwen-code'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'filesearch', 'findfiles', 'glob', 'listdirectory',
     'listfiles', 'ls', 'readfolder'
   );

UPDATE actions
   SET action_type = 'search_text'
 WHERE tool = 'qwen-code'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'findtext', 'grep', 'ripgrep', 'searchfilecontent',
     'searchtext'
   );

UPDATE actions
   SET action_type = 'spawn_subagent'
 WHERE tool = 'qwen-code'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'delegate', 'spawnagent', 'subagent', 'task'
   );

UPDATE actions
   SET action_type = 'todo_update'
 WHERE tool = 'qwen-code'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'todo', 'todowrite', 'updateplan'
   );

UPDATE actions
   SET action_type = 'user_prompt_expansion'
 WHERE tool = 'qwen-code'
   AND action_type = 'unknown'
   AND raw_tool_name = 'qwen-code.slash_command';

UPDATE actions
   SET action_type = 'web_fetch'
 WHERE tool = 'qwen-code'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'fetch', 'fetchurl', 'fetchwebpage', 'webfetch'
   );

UPDATE actions
   SET action_type = 'web_search'
 WHERE tool = 'qwen-code'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'googlewebsearch', 'search', 'websearch'
   );

UPDATE actions
   SET action_type = 'write_file'
 WHERE tool = 'qwen-code'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'create', 'createfile', 'write', 'writefile'
   );

UPDATE actions
   SET action_type = 'ask_user'
 WHERE tool = 'roo-code'
   AND action_type = 'unknown'
   AND raw_tool_name = 'ask_followup_question';

UPDATE actions
   SET action_type = 'browser_action'
 WHERE tool = 'roo-code'
   AND action_type = 'unknown'
   AND raw_tool_name = 'browser_action';

UPDATE actions
   SET action_type = 'edit_file'
 WHERE tool = 'roo-code'
   AND action_type = 'unknown'
   AND raw_tool_name = 'replace_in_file';

UPDATE actions
   SET action_type = 'mcp_call'
 WHERE tool = 'roo-code'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'access_mcp_resource', 'use_mcp_tool'
   );

UPDATE actions
   SET action_type = 'read_file'
 WHERE tool = 'roo-code'
   AND action_type = 'unknown'
   AND raw_tool_name = 'read_file';

UPDATE actions
   SET action_type = 'run_command'
 WHERE tool = 'roo-code'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'bash', 'cmd', 'cmd.exe', 'execute_command', 'powershell',
     'pwsh', 'sh'
   );

UPDATE actions
   SET action_type = 'search_files'
 WHERE tool = 'roo-code'
   AND action_type = 'unknown'
   AND raw_tool_name = 'list_files';

UPDATE actions
   SET action_type = 'search_text'
 WHERE tool = 'roo-code'
   AND action_type = 'unknown'
   AND raw_tool_name = 'search_files';

UPDATE actions
   SET action_type = 'task_complete'
 WHERE tool = 'roo-code'
   AND action_type = 'unknown'
   AND raw_tool_name = 'attempt_completion';

UPDATE actions
   SET action_type = 'write_file'
 WHERE tool = 'roo-code'
   AND action_type = 'unknown'
   AND raw_tool_name = 'write_to_file';

UPDATE actions
   SET action_type = 'edit_file'
 WHERE tool = 'zcode'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'apply_patch', 'applypatch', 'edit', 'multiedit', 'patch',
     'replace'
   );

UPDATE actions
   SET action_type = 'harness_call'
 WHERE tool = 'zcode'
   AND action_type = 'unknown'
   AND raw_tool_name = 'zcode.step_finish';

UPDATE actions
   SET action_type = 'read_file'
 WHERE tool = 'zcode'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'cat', 'read', 'view'
   );

UPDATE actions
   SET action_type = 'run_command'
 WHERE tool = 'zcode'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'bash', 'cmd', 'cmd.exe', 'command', 'powershell', 'pwsh',
     'shell'
   );

UPDATE actions
   SET action_type = 'search_files'
 WHERE tool = 'zcode'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'find', 'glob', 'ls'
   );

UPDATE actions
   SET action_type = 'search_text'
 WHERE tool = 'zcode'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'grep', 'rg', 'search'
   );

UPDATE actions
   SET action_type = 'spawn_subagent'
 WHERE tool = 'zcode'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'agent', 'subagent', 'task'
   );

UPDATE actions
   SET action_type = 'todo_update'
 WHERE tool = 'zcode'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'todo', 'todoread', 'todowrite'
   );

UPDATE actions
   SET action_type = 'web_fetch'
 WHERE tool = 'zcode'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'fetch', 'http', 'webfetch'
   );

UPDATE actions
   SET action_type = 'web_search'
 WHERE tool = 'zcode'
   AND action_type = 'unknown'
   AND raw_tool_name = 'websearch';

UPDATE actions
   SET action_type = 'write_file'
 WHERE tool = 'zcode'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'create', 'write'
   );

UPDATE actions
   SET action_type = 'edit_file'
 WHERE tool = 'zed'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'delete_path', 'edit_file'
   );

UPDATE actions
   SET action_type = 'read_file'
 WHERE tool = 'zed'
   AND action_type = 'unknown'
   AND raw_tool_name = 'read_file';

UPDATE actions
   SET action_type = 'run_command'
 WHERE tool = 'zed'
   AND action_type = 'unknown'
   AND raw_tool_name = 'terminal';

UPDATE actions
   SET action_type = 'search_files'
 WHERE tool = 'zed'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'find_path', 'list_directory'
   );

UPDATE actions
   SET action_type = 'write_file'
 WHERE tool = 'zed'
   AND action_type = 'unknown'
   AND raw_tool_name = 'write_file';

UPDATE actions
   SET action_type = 'ask_user'
 WHERE tool = 'zoo-code'
   AND action_type = 'unknown'
   AND raw_tool_name = 'ask_followup_question';

UPDATE actions
   SET action_type = 'browser_action'
 WHERE tool = 'zoo-code'
   AND action_type = 'unknown'
   AND raw_tool_name = 'browser_action';

UPDATE actions
   SET action_type = 'edit_file'
 WHERE tool = 'zoo-code'
   AND action_type = 'unknown'
   AND raw_tool_name = 'replace_in_file';

UPDATE actions
   SET action_type = 'mcp_call'
 WHERE tool = 'zoo-code'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'access_mcp_resource', 'use_mcp_tool'
   );

UPDATE actions
   SET action_type = 'read_file'
 WHERE tool = 'zoo-code'
   AND action_type = 'unknown'
   AND raw_tool_name = 'read_file';

UPDATE actions
   SET action_type = 'run_command'
 WHERE tool = 'zoo-code'
   AND action_type = 'unknown'
   AND raw_tool_name IN (
     'bash', 'cmd', 'cmd.exe', 'execute_command', 'powershell',
     'pwsh', 'sh'
   );

UPDATE actions
   SET action_type = 'search_files'
 WHERE tool = 'zoo-code'
   AND action_type = 'unknown'
   AND raw_tool_name = 'list_files';

UPDATE actions
   SET action_type = 'search_text'
 WHERE tool = 'zoo-code'
   AND action_type = 'unknown'
   AND raw_tool_name = 'search_files';

UPDATE actions
   SET action_type = 'task_complete'
 WHERE tool = 'zoo-code'
   AND action_type = 'unknown'
   AND raw_tool_name = 'attempt_completion';

UPDATE actions
   SET action_type = 'write_file'
 WHERE tool = 'zoo-code'
   AND action_type = 'unknown'
   AND raw_tool_name = 'write_to_file';

UPDATE actions
   SET action_type = 'edit_file'
 WHERE action_type = 'unknown'
   AND raw_tool_name IN (
     'apply_patch', 'edit_file'
   );

UPDATE actions
   SET action_type = 'read_file'
 WHERE action_type = 'unknown'
   AND raw_tool_name = 'read_file';

UPDATE actions
   SET action_type = 'run_command'
 WHERE action_type = 'unknown'
   AND raw_tool_name IN (
     'bash', 'cmd', 'cmd.exe', 'exec', 'powershell', 'pwsh',
     'run_command', 'sh', 'shell'
   );

UPDATE actions
   SET action_type = 'search_files'
 WHERE action_type = 'unknown'
   AND raw_tool_name = 'glob';

UPDATE actions
   SET action_type = 'search_text'
 WHERE action_type = 'unknown'
   AND raw_tool_name = 'grep';

UPDATE actions
   SET action_type = 'web_fetch'
 WHERE action_type = 'unknown'
   AND raw_tool_name = 'web_fetch';

UPDATE actions
   SET action_type = 'web_search'
 WHERE action_type = 'unknown'
   AND raw_tool_name = 'web_search';

UPDATE actions
   SET action_type = 'write_file'
 WHERE action_type = 'unknown'
   AND raw_tool_name = 'write_file';

UPDATE actions
   SET action_type = 'mcp_call'
 WHERE action_type = 'unknown'
   AND substr(raw_tool_name, 1, 5) = 'mcp__';
