#!/usr/bin/env bash
# Build/roll the org ACI image from a saved, private create-input. This does NOT
# migrate databases, change config, provision PostgreSQL, or rotate any key.
#
#   roll-org.sh vNN --build-only
#   roll-org.sh vNN --skip-build --base /private/postgres-create-input.yaml
#   roll-org.sh vNN --check-only --base /private/postgres-create-input.yaml
#   roll-org.sh rollback vNN
#
# A forward roll requires PostgreSQL secureValue DSNs. First cutover is staged:
# build-only -> quiesce + snapshot/migrate/verify -> explicit PG --base -> roll.
# State/sealing keys, log storage and object credentials are carried unchanged.
# Never roll PostgreSQL data back to an old SQLite image as an ordinary rollback.
set -euo pipefail
umask 077

RG=${RG:-superbased-demo-rg}
ACR=${ACR:-sbdemoacr35022}
REG="$ACR.azurecr.io"
GROUP=${GROUP:-sb-org}
ORG_URL=${ORG_URL:-http://sborg35022.eastus.azurecontainer.io:9443}
DEPLOY_DIR=${DEPLOY_DIR:-"$HOME/.observer-org-demo/deploy"}
export SECRET_KEY_FILE=${SECRET_KEY_FILE:-"$HOME/.observer-org-demo/org-secret.key"}
export GATEWAY_TOKEN_FILE=${GATEWAY_TOKEN_FILE:-"$HOME/.observer-org-demo/gateway.token"}
export CLICKHOUSE_ENV=${CLICKHOUSE_ENV:-"$HOME/.observer-org-demo/clickhouse.env"}
# Optional canonical DSN file paths (same file is legal for the first all-PG roll).
export CONTROL_DSN_FILE=${CONTROL_DSN_FILE:-}
export DATA_DSN_FILE=${DATA_DSN_FILE:-}

REPO_ROOT=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
cd "$REPO_ROOT"
MANIFEST_HELPER="$REPO_ROOT/scripts/roll-org-manifest.py"

die() { echo "roll-org: $*" >&2; exit 1; }
usage() { die "usage: roll-org.sh <version> [--build-only | --skip-build | --check-only] [--base <yaml>] | rollback <version> [--allow-legacy-rollback <verified-backup>]"; }

verify_secrets() {
    local input="$1"
    [ -f "$input" ] || die "create-input not found"
    if [ -n "$LEGACY_BACKUP" ]; then
        [ -s "$LEGACY_BACKUP" ] || die "legacy rollback requires a nonempty, separately verified backup file"
        echo "WARNING: emergency legacy rollback explicitly acknowledged; PostgreSQL writes are not copied into SQLite." >&2
        python3 "$MANIFEST_HELPER" verify "$input" --allow-legacy
    else
        python3 "$MANIFEST_HELPER" verify "$input"
    fi
}

verify_live() {
    local version="$1" attempt code actual ready health
    actual=$(az container show -g "$RG" -n "$GROUP" \
        --query "containers[?name=='observer-org'].image | [0]" -o tsv)
    [ "$actual" = "$REG/observer-org:$version" ] || die "running org image does not match requested version"
    echo "== poll application readiness (selected PostgreSQL stores + required durable log) =="
    for attempt in $(seq 1 45); do
        code=$(curl -s -o /dev/null -w '%{http_code}' -m 6 "$ORG_URL/readyz" 2>/dev/null || true)
        echo "  try $attempt: HTTP ${code:-000}"
        [ "$code" = "200" ] && break
        sleep 20
    done
    [ "$code" = "200" ] || die "readyz never reached 200; inspect observer-org container logs"
    ready=$(curl -fsS -m 8 "$ORG_URL/readyz")
    if [ -z "$LEGACY_BACKUP" ]; then
        # Liveness alone cannot prove a data-plane connection after cutover.
        python3 -c 'import json,sys; r=json.loads(sys.argv[1]); sys.exit(0 if r.get("status")=="ok" and int(r.get("control_schema_version",0))>0 and int(r.get("data_schema_version",0))>0 else 1)' "$ready" \
            || die "readyz lacks independent control/data migration proof"
    fi
    health=$(curl -fsS -m 8 "$ORG_URL/healthz")
    echo "  readyz: $ready"
    echo "  healthz: $health"
    echo "Focused estate data-count, enrolment, push/replay and egress/firewall checks remain operator steps."
}

build_image() {
    local source_rev build_work
    source_rev=$(git rev-parse --short HEAD)
    build_work=$(mktemp -d /tmp/sbo-org-image.XXXXXX)
    # This directory is exclusively generated by this invocation. Keep it on
    # failure for diagnosis; successful builds remove only this validated path.
    echo "== building observer-org:$VERSION from committed HEAD ($source_rev) =="
    git archive HEAD | tar -x -C "$build_work"
    [ -f "$build_work/Dockerfile.observer-org" ] || die "Dockerfile.observer-org missing from HEAD archive"
    (cd "$build_work" && az acr build -r "$ACR" -f Dockerfile.observer-org --build-arg VERSION="$VERSION" -t "observer-org:$VERSION" .)
    case "$build_work" in /tmp/sbo-org-image.*) rm -rf -- "$build_work" ;; *) die "unexpected build directory" ;; esac
}

ROLLBACK=false
if [ "${1:-}" = "rollback" ]; then ROLLBACK=true; shift; fi
VERSION=${1:-}
[[ "$VERSION" =~ ^[A-Za-z0-9_][A-Za-z0-9_.-]*$ ]] || usage
shift
MODE=roll
BASE=""
LEGACY_BACKUP=""
while [ "$#" -gt 0 ]; do
    case "$1" in
    --build-only|--skip-build|--check-only)
        [ "$MODE" = "roll" ] || usage
        MODE=${1#--}
        ;;
    --base)
        [ "$#" -ge 2 ] || usage
        BASE=$2
        shift
        ;;
    --allow-legacy-rollback)
        [ "$#" -ge 2 ] && "$ROLLBACK" || usage
        LEGACY_BACKUP=$2
        shift
        ;;
    *) usage ;;
    esac
    shift
done

if "$ROLLBACK"; then
    [ "$MODE" = "roll" ] && [ -z "$BASE" ] || usage
    BASE="$DEPLOY_DIR/sb-org-$VERSION.yaml"
elif [ "$MODE" = "build-only" ]; then
    [ -z "$BASE" ] || usage
    build_image
    echo "== image built; no config read, migration, or estate recreate performed =="
    exit 0
else
    [ -n "$BASE" ] || die "supply --base with a private PostgreSQL create-input"
fi

verify_secrets "$BASE"
if [ "$MODE" = "check-only" ]; then
    echo "== offline create-input checks passed; no Azure action performed =="
    exit 0
fi
if ! "$ROLLBACK"; then
    if [ "$MODE" != "skip-build" ]; then build_image; fi
    NEXT_INPUT="$DEPLOY_DIR/sb-org-$VERSION.yaml"
    # Structured retagging cannot alter another sidecar or leak a secret diff.
    python3 "$MANIFEST_HELPER" retag "$BASE" --image "$REG/observer-org:$VERSION" --output "$NEXT_INPUT"
    verify_secrets "$NEXT_INPUT"
    BASE=$NEXT_INPUT
fi
echo "== recreating $GROUP from verified private create-input =="
az container create -g "$RG" --file "$BASE" -o none
verify_live "$VERSION"
echo "== org roll to $VERSION complete =="
