package cloudevidence

import (
	"strconv"
	"strings"
	"testing"

	"github.com/marmutapp/superbased-observer/internal/cloudcontract"
	"github.com/marmutapp/superbased-observer/internal/dataauthority"
	"github.com/marmutapp/superbased-observer/internal/scrub"
)

func TestSelectExcerptsSkipsHarnessPromptsAndStripsPasteBars(t *testing.T) {
	texts := SessionTexts{
		UserPrompts: []string{
			"<command-name>/clear</command-name>\n<command-message>clear</command-message>",
			"<local-command-caveat>Caveat: The messages below were generated by the user</local-command-caveat>",
			"<system-reminder>do a thing</system-reminder>",
			"▎ Continue work on the repo\n▎\n▎ First, read the handover doc.",
			// The same prompt captured twice by two adapters (a short target row
			// and a full body row) must spend only one excerpt of the budget.
			"▎ Continue work on the repo\n▎\n▎ First, read the handover doc. And then keep going for a while longer.",
			"Please push everything to private origin as well.",
		},
	}
	got := SelectExcerpts(texts, false)
	if len(got) < 2 {
		t.Fatalf("got %d excerpts, want at least the first prompt and one more: %+v", len(got), got)
	}
	if got[0].Source != SourceFirstUserPrompt {
		t.Fatalf("first excerpt source = %q, want %q", got[0].Source, SourceFirstUserPrompt)
	}
	if !strings.HasPrefix(got[0].Text, "Continue work on the repo") {
		t.Errorf("paste bars were not stripped: %q", got[0].Text)
	}
	for _, e := range got {
		if strings.HasPrefix(e.Text, "<command-name>") ||
			strings.HasPrefix(e.Text, "<local-command-caveat>") ||
			strings.HasPrefix(e.Text, "<system-reminder>") {
			t.Errorf("a harness-injected prompt reached the excerpt set: %q", e.Text)
		}
		if e.CapBytes != ExcerptCapBytes {
			t.Errorf("excerpt %q cap = %d, want %d", e.Source, e.CapBytes, ExcerptCapBytes)
		}
	}
	if len(got) != 3 {
		t.Errorf("got %d excerpts, want 3 (duplicate prompt deduped): %+v", len(got), got)
	}
}

func TestSelectExcerptsOrderPriorityAndBounds(t *testing.T) {
	prompts := make([]string, 40)
	for i := range prompts {
		prompts[i] = "prompt number " + refIndex(i) + " with enough words to be distinct"
	}
	texts := SessionTexts{
		UserPrompts:           prompts,
		FinalAssistantMessage: "wrapped up the work",
		Errors:                []string{"Exit code 1", "Command timed out after 30s", "EACCES: permission denied"},
	}
	got := SelectExcerpts(texts, false)
	if len(got) > cloudcontract.MaxContextExcerpts {
		t.Fatalf("got %d excerpts, exceeds MaxContextExcerpts %d", len(got), cloudcontract.MaxContextExcerpts)
	}
	wantOrder := []string{SourceFirstUserPrompt}
	for i := 0; i < maxSpreadUserPrompts; i++ {
		wantOrder = append(wantOrder, SourceUserPrompt)
	}
	wantOrder = append(wantOrder,
		SourceFinalAssistantMessage,
		// Three distinct failure classes, each seen once: the two top-ranked
		// (ties broken by first appearance) plus the LAST observed one.
		SourceErrorClass, SourceErrorClass, SourceErrorClassLast,
	)
	if len(got) != len(wantOrder) {
		t.Fatalf("got %d excerpts, want %d: %+v", len(got), len(wantOrder), got)
	}
	for i, w := range wantOrder {
		if got[i].Source != w {
			t.Errorf("excerpt %d source = %q, want %q", i, got[i].Source, w)
		}
	}
	// The spread must reach the END of the session, not just its opening.
	if last := got[maxSpreadUserPrompts]; !strings.Contains(last.Text, "number 39") {
		t.Errorf("last sampled prompt = %q, want the session's final prompt", last.Text)
	}
}

// TestSelectExcerptsKeepsEveryPromptWhenTheSessionIsShort pins the 2026-09-16
// ruling's other half: a session with at most 1 + maxSpreadUserPrompts real
// prompts ships EVERY one of them, in order - no striding, nothing skipped.
func TestSelectExcerptsKeepsEveryPromptWhenTheSessionIsShort(t *testing.T) {
	n := 1 + maxSpreadUserPrompts
	prompts := make([]string, n)
	for i := range prompts {
		prompts[i] = "prompt number " + refIndex(i) + " with enough words to be distinct"
	}
	got := SelectExcerpts(SessionTexts{UserPrompts: prompts}, false)
	if len(got) != n {
		t.Fatalf("got %d excerpts, want every one of the %d prompts: %+v", len(got), n, got)
	}
	for i, e := range got {
		if !strings.Contains(e.Text, "number "+refIndex(i)+" ") {
			t.Errorf("excerpt %d = %q, want prompt %d (in order, none skipped)", i, e.Text, i)
		}
	}
}

// TestErrorExcerptsCarryOnlyClosedClassLabels is the F1 privacy pin: a recorded
// tool_failure message is raw tool OUTPUT (hooks copy the failing command's
// body, which can embed stdout such as `customer_balance=12345`). No substring
// of that message may ever reach an excerpt — only a closed-vocabulary CLASS.
func TestErrorExcerptsCarryOnlyClosedClassLabels(t *testing.T) {
	const (
		stdoutShaped = "customer_balance=12345 account=ACME-77 rows=3"
		errPrefixed  = "Error: customer_balance=12345 account=ACME-77"
	)
	got := SelectExcerpts(SessionTexts{
		UserPrompts: []string{"do the thing"},
		Errors: []string{
			stdoutShaped,
			errPrefixed,
			"Exit code 1\ncustomer_balance=12345",
			"File content (9.2MB) exceeds maximum allowed size\n<file body>",
		},
	}, false)

	classes := 0
	for _, e := range got {
		if !isErrorClassSource(e.Source) {
			continue
		}
		classes++
		class, count := splitErrorClassText(t, e.Text)
		if !errorClassVocabulary()[class] {
			t.Errorf("error excerpt text %q is not a closed class label plus a count", e.Text)
		}
		if count < 1 {
			t.Errorf("error excerpt %q carries a non-positive count", e.Text)
		}
		if e.CapBytes != ErrorClassCapBytes {
			t.Errorf("error excerpt cap = %d, want %d", e.CapBytes, ErrorClassCapBytes)
		}
		if len(e.Text) > ErrorClassCapBytes {
			t.Errorf("error excerpt %q exceeds its %d-byte cap", e.Text, ErrorClassCapBytes)
		}
	}
	if classes == 0 {
		t.Fatal("no error_class excerpt was emitted for classifiable failures")
	}
	if classes > maxErrorExcerptsTotal {
		t.Fatalf("emitted %d error classes, exceeds the %d bound", classes, maxErrorExcerptsTotal)
	}
	for _, e := range got {
		if isErrorClassSource(e.Source) {
			continue
		}
		if strings.Contains(e.Text, "customer_balance") || strings.Contains(e.Text, "ACME-77") {
			t.Fatalf("an error message body reached a non-error excerpt: %q", e.Text)
		}
	}

	// End to end: the message bytes must not be in the envelope at all.
	in := baseInput()
	in.Excerpts = got
	opts := structuralOpts()
	opts.GrantedPurposes = append(opts.GrantedPurposes, cloudcontract.PurposeContextEnrichment)
	env, err := BuildEnvelope(in, cloudcontract.PlanePersonal, opts)
	if err != nil {
		t.Fatalf("BuildEnvelope: %v", err)
	}
	bytesOut, _, err := Serialize(env)
	if err != nil {
		t.Fatalf("Serialize: %v", err)
	}
	for _, forbidden := range []string{"customer_balance", "12345", "ACME-77", "Exit code 1", "9.2MB", "file body"} {
		if strings.Contains(string(bytesOut), forbidden) {
			t.Errorf("error-message bytes %q reached the envelope", forbidden)
		}
	}
}

// isErrorClassSource reports whether a source is one of the two error-class
// lanes (the top-by-count entries and the last-observed entry).
func isErrorClassSource(source string) bool {
	return source == SourceErrorClass || source == SourceErrorClassLast
}

// splitErrorClassText splits the "<class> x<count>" excerpt text. A text that is
// not in that exact shape fails the test — the shape IS the privacy guarantee.
func splitErrorClassText(t *testing.T, text string) (string, int) {
	t.Helper()
	i := strings.LastIndex(text, " x")
	if i < 0 {
		t.Fatalf("error excerpt %q is not in <class> x<count> form", text)
	}
	n, err := strconv.Atoi(text[i+2:])
	if err != nil {
		t.Fatalf("error excerpt %q does not end in an integer count: %v", text, err)
	}
	return text[:i], n
}

// TestErrorClassesCountTheWholePopulation is the Q1 honesty pin: the classes
// that ship are the most FREQUENT ones over every failure handed in — with the
// counts — not the first two distinct classes of the earliest handful.
func TestErrorClassesCountTheWholePopulation(t *testing.T) {
	var errs []string
	// A noisy early class, a dominant later class, a rarer one, and a DIFFERENT
	// class at the very end.
	for i := 0; i < 3; i++ {
		errs = append(errs, "ENOENT: no such file or directory")
	}
	for i := 0; i < 40; i++ {
		errs = append(errs, "--- FAIL: TestThing (0.01s)")
	}
	for i := 0; i < 9; i++ {
		errs = append(errs, "Command timed out after 30s")
	}
	errs = append(errs, "EACCES: permission denied")

	got := selectErrorClasses(errs)
	want := []struct {
		source string
		text   string
	}{
		{SourceErrorClass, "test_failure x40"},
		{SourceErrorClass, "timeout x9"},
		{SourceErrorClassLast, "permission_denied x1"},
	}
	if len(got) != len(want) {
		t.Fatalf("got %d error excerpts, want %d: %+v", len(got), len(want), got)
	}
	for i, w := range want {
		if got[i].Source != w.source || got[i].Text != w.text {
			t.Errorf("excerpt %d = (%q,%q), want (%q,%q)", i, got[i].Source, got[i].Text, w.source, w.text)
		}
	}
	// Determinism: the same population always selects the same set in the same
	// order (the two-digest rebuild protocol depends on it).
	if again := selectErrorClasses(errs); len(again) != len(got) {
		t.Fatalf("second selection differs in length")
	} else {
		for i := range got {
			if again[i] != got[i] {
				t.Fatalf("selection is not deterministic at %d: %+v vs %+v", i, again[i], got[i])
			}
		}
	}
}

// TestErrorClassLastOmittedWhenItIsAlreadyTop pins that the third slot is spent
// only when it says something new.
func TestErrorClassLastOmittedWhenItIsAlreadyTop(t *testing.T) {
	got := selectErrorClasses([]string{
		"--- FAIL: TestA", "Command timed out after 5s", "--- FAIL: TestB",
	})
	if len(got) != 2 {
		t.Fatalf("got %d excerpts, want 2 — the last class is already a top class: %+v", len(got), got)
	}
	for _, e := range got {
		if e.Source != SourceErrorClass {
			t.Errorf("unexpected source %q", e.Source)
		}
	}
}

// TestExcerptBudgetFitsWithinTheContractBound pins the arithmetic that keeps the
// error classes from ever being the entries that get dropped: the maximum
// selectable set must fit inside MaxContextExcerpts.
func TestExcerptBudgetFitsWithinTheContractBound(t *testing.T) {
	if max := 1 + maxSpreadUserPrompts + 1 + maxErrorExcerptsTotal; max > cloudcontract.MaxContextExcerpts {
		t.Fatalf("the excerpt budget sums to %d, exceeding MaxContextExcerpts %d", max, cloudcontract.MaxContextExcerpts)
	}
	prompts := make([]string, 40)
	for i := range prompts {
		prompts[i] = "prompt number " + refIndex(i) + " with enough words to be distinct"
	}
	got := SelectExcerpts(SessionTexts{
		UserPrompts:           prompts,
		FinalAssistantMessage: "wrapped up",
		Errors: []string{
			"--- FAIL: TestA", "--- FAIL: TestB", "Command timed out after 5s",
			"EACCES: permission denied",
		},
	}, false)
	if len(got) > cloudcontract.MaxContextExcerpts {
		t.Fatalf("a maximal selection produced %d excerpts, exceeding %d", len(got), cloudcontract.MaxContextExcerpts)
	}
	if got[len(got)-1].Source != SourceErrorClassLast {
		t.Errorf("the last-observed class was dropped from a maximal selection: %+v", got)
	}
}

// TestErrorClassVocabularyMatchesTheContract is the N5 drift pin: the labels
// this package emits are exactly the ones cloudcontract publishes to the hosted
// prompt builder. A class added on one side and not the other fails here.
func TestErrorClassVocabularyMatchesTheContract(t *testing.T) {
	contract := map[string]bool{}
	for _, c := range cloudcontract.ErrorClasses() {
		contract[c] = true
	}
	fromRules := map[string]bool{}
	for _, r := range errorClassRules {
		fromRules[r.class] = true
		if !contract[r.class] {
			t.Errorf("rule label %q is not in cloudcontract.ErrorClasses()", r.class)
		}
	}
	for c := range contract {
		if !fromRules[c] {
			t.Errorf("contract label %q has no classification rule — it can never be emitted", c)
		}
	}
}

// TestClassifyErrorMessage pins the pattern table, including the "unknown means
// OMIT" rule that keeps an unrecognized message from shipping at all.
func TestClassifyErrorMessage(t *testing.T) {
	cases := []struct{ in, want string }{
		{"Exit code 1", "exit_code_nonzero"},
		{"command exited with status 2", "exit_code_nonzero"},
		{"Command timed out after 120s", "timeout"},
		{"ENOENT: no such file or directory, open 'x'", "file_not_found"},
		{"EACCES: permission denied", "permission_denied"},
		{"File content (9.2MB) exceeds maximum allowed size", "file_too_large"},
		{"syntax error near unexpected token", "syntax_error"},
		{"--- FAIL: TestThing (0.01s)", "test_failure"},
		{"dial tcp: connection refused", "network_error"},
		{"429 too many requests", "rate_limited"},
		{"customer_balance=12345 account=ACME-77", ""},
		{"", ""},

		// N8: a SPECIFIC class must win over the generic transport class, even
		// when the specific failure's own output mentions a transport error.
		{"--- FAIL: TestDial (0.02s)\n    dial tcp: connection refused", "test_failure"},
		{"assertion failed: got 3, want 4 (connection reset by peer in log)", "test_failure"},
		{"syntax error: unexpected token, and the connection refused later", "syntax_error"},
		// A genuine transport failure with no more specific cause still lands
		// on network_error.
		{"dial tcp 10.0.0.1:443: connect: connection refused", "network_error"},
		{"lookup api.example.com: no such host", "network_error"},
		{"dns resolution failed for the upstream", "network_error"},
		// N8: the over-broad phrases no longer fire on incidental substrings.
		{"wrote 429 bytes to /tmp/out", ""},
		{"failed to read /etc/dnsmasq.conf", ""},
		{"resolved dnsutils package metadata", ""},
		{"HTTP 429 from the provider", "rate_limited"},
		{"upstream returned status 429", "rate_limited"},
	}
	for _, tc := range cases {
		if got := classifyErrorMessage(tc.in); got != tc.want {
			t.Errorf("classifyErrorMessage(%q) = %q, want %q", tc.in, got, tc.want)
		}
	}
}

func TestSelectExcerptsTitleOnlyIsJustTheFirstPrompt(t *testing.T) {
	got := SelectExcerpts(SessionTexts{
		UserPrompts:           []string{"do the thing", "and the other thing"},
		FinalAssistantMessage: "done",
		Errors:                []string{"boom"},
	}, true)
	if len(got) != 1 || got[0].Source != SourceFirstUserPrompt {
		t.Fatalf("title-only selection = %+v, want exactly one first_user_prompt", got)
	}
}

func TestSelectExcerptsEmpty(t *testing.T) {
	if got := SelectExcerpts(SessionTexts{}, false); len(got) != 0 {
		t.Errorf("empty substrate produced %+v", got)
	}
	if got := SelectExcerpts(SessionTexts{UserPrompts: []string{"<system-reminder>x</system-reminder>"}}, false); len(got) != 0 {
		t.Errorf("harness-only substrate produced %+v", got)
	}
}

// TestExcerptsRequireContextPurpose pins the consent gate end to end: the SAME
// input built under the structural purpose carries no content at all.
func TestExcerptsRequireContextPurpose(t *testing.T) {
	in := baseInput()
	in.Excerpts = SelectExcerpts(SessionTexts{
		UserPrompts: []string{"wire the retry-safe device auth flow"},
	}, false)
	if len(in.Excerpts) != 1 {
		t.Fatalf("fixture selection produced %d excerpts", len(in.Excerpts))
	}

	structural, err := BuildEnvelope(in, cloudcontract.PlanePersonal, structuralOpts())
	if err != nil {
		t.Fatalf("structural build: %v", err)
	}
	if len(structural.Context) != 0 {
		t.Fatalf("structural envelope carried %d excerpts — content leaked past the purpose gate", len(structural.Context))
	}
	bytesOut, _, err := Serialize(structural)
	if err != nil {
		t.Fatalf("serialize: %v", err)
	}
	if strings.Contains(string(bytesOut), "retry-safe") {
		t.Fatal("excerpt text appeared in structural upload bytes")
	}

	contextual, err := BuildEnvelope(in, cloudcontract.PlanePersonal, BuildOptions{
		Scrubber:        scrub.New(),
		ScrubberVersion: "scrub-v1",
		GrantedPurposes: []cloudcontract.Purpose{cloudcontract.PurposeContextEnrichment},
	})
	if err != nil {
		t.Fatalf("context build: %v", err)
	}
	if len(contextual.Context) != 1 {
		t.Fatalf("context envelope carried %d excerpts, want 1", len(contextual.Context))
	}
	if contextual.Context[0].Source != SourceFirstUserPrompt {
		t.Errorf("source = %q, want %q", contextual.Context[0].Source, SourceFirstUserPrompt)
	}
	// The excerpt's own source label must be a citable evidence ref.
	if _, ok := cloudcontract.AllowedEvidenceRefs(*contextual)[SourceFirstUserPrompt]; !ok {
		t.Error("first_user_prompt is not an allowed evidence ref")
	}
	_ = dataauthority.AuthorityPersonal // keep the import honest about what the fixture asserts
}
